HKUDS/LightRAG

README.md

In the readme for the repository, there is a reference to the utils.jpeg file, but the correct file extension is .py
Edit:
Fixes #5

Fix typo on readme: utils.jpeg -> utils.py

---

.gitignore
examples/lightrag_bedrock_demo.py
lightrag/llm.py
requirements.txt

This PR adds support for [Amazon Bedrock](https://aws.amazon.com/bedrock/) LLMs via [Converse API](https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html) and Embedding models (Titan + Cohere) with [`InvokeModel`](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModel.html). Implementation is based on `async` calls via [`aioboto3`](https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html) cf. https://github.com/terricain/aioboto3/issues/341 for additional info.
**Example:**
```python
"""
LightRAG meets Amazon Bedrock ⛰️
"""
import os
import logging
from lightrag import LightRAG, QueryParam
from lightrag.llm import bedrock_complete, bedrock_embedding
from lightrag.utils import EmbeddingFunc …
```

feat: Amazon Bedrock support ⛰️

---

README.md
examples/lightrag_siliconcloud_demo.py
lightrag/llm.py
requirements.txt

1. 增加免费的 siliconcloud API 支持
2. 调整指数退避参数 `wait=wait_exponential(multiplier=1, min=4, max=60),` ，因为 API 算费用单位是 minute，最大应该是 60 秒
已自测可以正常跑，这是我的可视化（7B 免费模型）：

feat(examples): support siliconcloud free API

---

examples/lightrag_siliconcloud_demo.py

bce 底层用的 512 token （转中文大约 1.5 倍）
参数 assign 错了，给太长会报错。

fix(lightrag_siliconcloud_demo.py): max_token_size

---

examples/lightrag_siliconcloud_demo.py
lightrag/llm.py

- according to current hf code in llm.py, it will initailize a new hf_model object everytime the function is invoke, which causing duplicate loading model in gpu and cause oom.
- this pr cache the hf_model with lru_cache, so that it will not load a new model everytime when the function is invoke.
- before:
- after:

[FIX] fix infinite loading hf model bug that cause oom

---

lightrag/llm.py

- the current `response_text` in `hf_model_if_cache` will contain user prompt as shown as follows:
-  even though the response_text is being stripped in `operate.py` which make the final response look like normally, but in the process of creating the knowledge graph and vector databse (entity extraction phase), the user prompt is not strip, which will result the prompt `PROMPTS["entity_extraction"]` in `prompt.py` will also consider as assitant response as well and causes the entity in example prompt is being extracted, but these entity is not actually in the text file (pure text database), instead, it just an example entity.
- what does thir pr do: remove user prompt in response as shown as follows:

[FIX] fix hf output bug (current output contain user prompt which cause logical error in entity extraction phase)

---

lightrag/lightrag.py

Before, the `finally` block would always call `_insert_done()`, which writes out the `vdb_*` and `kv_store_*` files ... even if there was nothing to insert (because all docs had already been inserted).  This was causing the speed of skippable inserts to become very slow as the graph grew.

Only update storage if there was something to insert

---

lightrag/kg/neo4j_impl.py
lightrag/lightrag.py

fix the bug which describe in issue #269, and I found neo4j would threw ClientError when thread pool is overload. so I add a retry Exception by the way.
修复了#269 问题，然后我发现当线程池不够用的时候，neo4j会抛出ClientError，所以顺手加了一个重试的异常

fix neo4j bug

---

lightrag/operate.py

When I using LightRAG, my model will generate **text below** for keyword extraction, it contains two `"{"`, when using `"{" + result.split("{")[1].split("}")[0] + "}"`, it fails, but using `"{" + result.split("{")[-1].split("}")[0] + "}"` is ok, and the original expectation still achieved.
To extract high-level and low-level keywords from the given query, we will use Natural Language Processing (NLP) techniques.
```python
import json
import re
def extract_keywords(query):
query = query.lower()
tokens = re.findall(r'\b\w+\b', query)
high_level_keywords = []
low_level_keywords = []
stop_words = ['the', 'and', 'a', 'an', 'in', 'on', 'at', 'by', 'with']
for token in tokens:
if token not in stop_words:
if len(token.split()) > 1:
high_level_keywords.append(token)
else: …
```

A more robust approach for result to json.

---

examples/lightrag_azure_openai_demo.py

原先的AzureAI的Demo在调用构建知识图谱时会超过接口速率限制，无重试机制，导致构建图谱失败。现在修改为使用AzureOpenAI官方SDK实现

使用AzureOpenAI实现，支持RPM/TPM限制。修复原先429响应即抛出异常的问题

---

lightrag/operate.py

您好，看到您的项目对我很有启发。但我在使用 local search 时，发现源码中`/LightRAG/lightrag/operate.py`  在召回实体最相关文本单元`_find_most_related_text_unit_from_entities`函数的时候，为了对文本单元重要性进行排序所使用到了relation_counts。
但在现有的逻辑中，如果一个文本单元c_id与多个实体节点相关联，且这些实体节点的一跳相邻节点数量不同，那么先遍历到一跳相邻节点少的实体节点时，relation_counts可能会被低估。
所以我修改为：在每次遍历时更新relation_counts，而不是跳过已经存在的文本单元。

fix: 修改了local search中的relation_counts计数规则

---

lightrag/operate.py
lightrag/prompt.py

resolves #342 
- Replace hardcoded chinese language in prompts with templated language
- Template missed instance of English language
- Adjust usage of fixed prompts to supply language as context

fix templating of language in prompts

---

README.md

- The `Using Neo4J for Storage` section was originally nested inside the Ollama details block, making it less visible to users looking for KG storage options.
- Moved this section to appear just before Insert Custom KG, grouping it with other Knowledge Graph-related content.
- This change improves visibility and helps users discover Neo4J configuration details more easily.

Update README: Move Neo4J Storage Section for Better Visibility

---

lightrag/llm.py
lightrag/operate.py
lightrag/utils.py

#287 
- Added `keyword_extraction=False` to all `*_complete` functions. If `True`, each function handles its own JSON mode logic.
- Moved `locate_json_string_body_from_string` to `*_complete` functions as the default JSON logic for `keyword_extraction`.

JSON mode support for ollama and openai gpt

---

lightrag/lightrag.py

function was returning a closed event loop.

fix for #209

---

lightrag/llm.py

+ The "azure_openai_embedding" function was missing the "api_version" argument.
Previously, it was only read from an environment variable not passed from the user.
+ The "max_token_size" was incorrect. Now it corrected to 8191, according to OpenAI documentation.
https://platform.openai.com/docs/guides/embeddings/#embedding-models

Azure OpenAI Embedding

---

lightrag/operate.py
lightrag/prompt.py

1. examples in the latest main branch was changed to be cutomizable, but a bug was introduced, that the string literal format is missing for the `PROMPTS["entity_extraction_examples"` in `lightrag/prompt.py` . It is directly used in the line 265 of `lightrag/operate.py` without formating.
2. fixed a typo (missing right bracket) in the system prompt for entity extraction.

fix examples' prompt bug

---

README.md
examples/lightrag_openai_compatible_demo_embedding_cache.py
lightrag/lightrag.py
lightrag/llm.py
lightrag/utils.py

- 在 LightRAG 类中添加 embedding_cache_config配置项
- 实现基于 embedding 相似度的缓存查询和存储
- 添加量化和反量化函数，用于压缩 embedding 数据
- 新增示例演示 embedding 缓存的使用
- 基于相似度的缓存可以有效的减少LLM的开销，极大提高相似问题的查询效率

添加查询时使用embedding缓存功能

---

examples/lightrag_api_open_webui_demo.py
examples/lightrag_ollama_demo.py
lightrag/base.py
lightrag/llm.py
lightrag/operate.py

#77 and #93
`lightrag_api_open_webui_demo.py` is a demo API server that mocks the Ollama API, enabling  integration with the [Open-WebUI](https://github.com/open-webui/open-webui). The default RAG implementation in Open-WebUI lacks sufficient quality.

Add support for Ollama streaming output and integrate Open-WebUI as the chat UI demo

---

README.md
lightrag/lightrag.py
lightrag/llm.py
lightrag/operate.py
lightrag/prompt.py
lightrag/utils.py

- 在 embedding 缓存配置中添加 use_llm_check 参数
- 实现 LLM 相似性检查逻辑，作为缓存命中的二次验证- 优化 naive 模式的缓存处理流程
- 调整缓存数据结构，移除不必要的 model 字段
- 2023年的销售额
- 2024年的销售额

优化embedding相似度缓存机制，增加 LLM 相似性检查功能并优化缓存机制

---

examples/lightrag_openai_compatible_stream_demo.py
lightrag/llm.py

Add support for OpenAI Compatible Streaming output and delete unreachable code

---

README.md
lightrag/llm.py
lightrag/operate.py
lightrag/prompt.py

- 只有实体没有关系时，继续处理，而不是直接return
- 当只有实体而没有关系的图片在高阶查询关系时会返回空，这里优化返回，当没有关系时降级为local查询

fix(lightrag): 修复只有实体没有关系的chunk处理逻辑

---

lightrag/kg/chroma_impl.py
lightrag/lightrag.py
test_chromadb.py

- Implemented `ChromaVectorDBStorage` class in `lightrag/kg/chroma_impl.py` to support ChromaDB as a vector storage backend.
- Updated `lightrag.py` to include `ChromaVectorDBStorage` in the storage class mapping.
- Added a test script `test_chromadb.py` to demonstrate the usage of ChromaDB with LightRAG, including configuration for embedding functions and ChromaDB connection settings.
- fix lazy import function to support package context for dynamic class loading. https://github.com/HKUDS/LightRAG/pull/444/commits/288d4b8355eb3fd1fdfaf165f1380501b58aaf67

feat: Add ChromaDB integration for vector storage

---

examples/lightrag_tidb_demo.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py
requirements.txt

support tidb cloud
- add TiDBKVStorage
- add TiDBVectorDBStorage

support TiDB: add TiDBKVStorage, TiDBVectorDBStorage

---

lightrag/kg/milvus_impl.py
lightrag/storage.py

The asyncio.as_completed() function does not guarantee that the results are ordered
When using this project, I found that the entities and relationships of the recall were somewhat related to the low-level keywords and the high-level keyword, but it was not very related, and I felt that the ability of the vector model was not fully utilized, it maybe a strange problem. 
I looked at the code of inserting vectors and found problem. ```asyncio.as_completed```  is used incorrectly, ```asyncio.as_completed``` results are not returned in the order in input tasks, but in the order in which the tasks were completed. I changed to use ```asyncio.gather``` to make sure the results were orderly. And ensure that ```tqdm``` works properly.
This code need ```asyncio.as_completed``` results were orderly …

Maybe very important!!! Fix embedding error

---

lightrag/lightrag.py

背景：
1. enable_llm_cache=False时，llm_response_cache 赋值为None
2. 在lightrag.py中，hashing_kv在原代码中直接赋值为llm_response_cache ，直接导致所有依赖hashing_kv传值的对象报错
3. 所有查询依赖于llm.py中的xxx_model_complete方法，而方法需要hashing_kv获取model_name，最终导致恶性bug
4. 考虑到hashing_kv的使用，选择了修改hashing_kv的初始化逻辑实现改动最小化
- 修改了 llm_model_func 和 query 方法中的hashing_kv初始化逻辑
- 当 self.llm_response_cache 不存在或没有 global_config 属性时，会创建一个新的hashing_kv实例
- 所有基于hashing_kv获取global_config属性的对象可以正常运行
Background:
1. If enable_llm_cache=False, llm_response_cache is set to None
2. In lightra.py, hashing_kv is directly assigned to llm_response_cache in the original code, which directly causes all objects that rely on hashing_kv to report an error
3. All queries rely on the xxx_model_complete method in llm.py, which requires hashing_kv to get model_name, resulting …

refactor(lightrag): 优化hashing_kv初始化逻辑

---

lightrag/lightrag.py

背景：query的四种模式对hashing_kv的依赖不一样，干脆复用llm_response_cache的初始化逻辑，防止其他初始化问题
- hybrid模式对hashing_kv的依赖不止global_config，需要加入其他属性的初始化

fix(llm): hashing_kv初始化修复

---

examples/lightrag_tidb_demo.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py

implement graph storage by tidb
- add `TiDBGraphStorage`

support TiDBGraphStorage

---

examples/lightrag_ollama_gremlin_demo.py
lightrag/kg/gremlin_impl.py
lightrag/lightrag.py
requirements.txt

Add Gremlin graph storage.
Note that at least my setup suffered from an `anyio` issue, that has been fixed a couple of days ago, with commit https://github.com/agronholm/anyio/commit/c518300593f2411196fd492d917269dcb6f7682b so I had to install it from git before the next version is released.

Add Gremlin graph storage

---

lightrag/utils.py

- 在 handle_cache 函数中添加了对 global_config 中 enable_l`lm_cache 设置的检查
- 如果配置禁用了缓存，则直接返回 None -这个修改确保了在不需要缓存的情况下，函数能够正确地跳过缓存处理

fix(utils): 修复缓存未正确启用的问题

---

lightrag/prompt.py

hi, thanks for your great work. 
when I ran lightrag_azure_openai_demo.py, 
I found that there were some problems with the format of ‘keywords_extraction_examples’. 
```
{{
"high_level_keywords": ["International trade", "Global economic stability", "Economic impact"],
"low_level_keywords": ["Trade agreements", "Tariffs", "Currency exchange", "Imports", "Exports"]
}}
```
it  caused unexpected output.
I fixed the format of keywords_extraction_examples and it seems to work well now.

fix keywords_extraction_examples format error

---

lightrag/kg/age_impl.py

When running with Apache AGE impl on Windows (with psycopg), it will got async loop error, the fix is to register asyncio with WindowsSelectorEventLoopPolicy. Only effect on Windows. Tested okay.

Fix the async issue while running on Windows

---

lightrag/llm.py

we should use `APITimeoutError` instead of `Timeout` in `retry_if_exception_type` because `Timeout` is not a a kind of `BaseException`. But `retry_if_exception_type`  needs the input type to be `BaseException`.
```
class retry_if_exception_type(retry_if_exception):
"""Retries if an exception has been raised of one or more types."""
def __init__(
self,
exception_types: typing.Union[
typing.Type[BaseException],
typing.Tuple[typing.Type[BaseException], ...],
] = Exception,
) -> None:
self.exception_types = exception_types
super().__init__(lambda e: isinstance(e, exception_types))
```

fix: change exception type

---

README.md
lightrag/api/azure_openai_lightrag_server.py
lightrag/api/lollms_lightrag_server.py
lightrag/api/ollama_lightrag_server.py
lightrag/api/openai_lightrag_server.py

This PR implements optional API key authentication across all FastAPI services in LightRAG. The implementation provides flexible security that can be enabled or disabled through configuration.
Key Changes:
- Added optional API key authentication system across all FastAPI endpoints
- Authentication can be configured through environment variable `LIGHTRAG_API_KEY` or command line argument
- Services run without authentication when no API key is configured
- Implemented proper security headers and API key validation
- Added OpenAPI documentation support for API key authentication
Implementation Details:
- Used FastAPI's built-in security utilities for robust authentication
- Added `X-API-Key` header support for API authentication
- Implemented graceful fallback to no-auth when API key is not …

Add Optional API Key Authentication to FastAPI Services

---

lightrag/operate.py

Keep the logic in  `kg_query` and `_build_query_context `consistent, and avoid duplicate and redundant processing.

Fix:Optimized logic for automatic switching modes when keywords do not exist

---

lightrag/lightrag.py

Makes the split_by_character parameter optional in ainsert method to maintain backwards compatibility with existing code.
Details:
The ainsert method in LightRAG class was recently modified to include a new split_by_character parameter
This change broke backwards compatibility for code using the previous method signature
Fixed by making split_by_character parameter optional with a default value of None
Impact:
Restores compatibility with existing code using the old method signature
Maintains new functionality for users who want to use character splitting
No breaking changes

Restore backwards compatibility for LightRAG's ainsert method

---

lightrag/api/lightrag_server.py

The `/documents/text` endpoint was throwing a 500 error because it attempted to call `len()` on the `rag` object which is not iterable. This occurred in the response where we tried to return the document count.
Modified the endpoint to return a fixed value of 1 for document_count since we're inserting a single text document. This resolves the 500 error while maintaining accurate document counting logic.
- Replaced `len(rag)` with hardcoded value `1` in the response
- Keeps all other functionality intact
- Verified the endpoint now successfully processes text insertions without 500 errors
- Response structure remains unchanged
- API contract is maintained
```python
document_count=len(rag)  # Caused 500 error
document_count=1  # Fixed value for single document insertion

Fix 500 error in LightRAG's API insert_text endpoint

---

lightrag/llm.py

Fixes #596
Update `azure_openai_complete` function to accept a model parameter with a default value of 'gpt-4o-mini'.
* Modify the function signature of `azure_openai_complete` to include a `model` parameter with a default value of 'gpt-4o-mini'.
* Pass the `model` parameter to the `azure_openai_complete_if_cache` function instead of the hardcoded model name 'conversation-4o-mini'.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/HKUDS/LightRAG/pull/597?shareId=02597a66-de1e-4ed7-86de-cfb268e43082).

Fixes #596 - Hardcoded model deployment name in azure_openai_complete

---

.env.example
lightrag/api/README.md
lightrag/api/lightrag_server.py

- Modified API key handling in lightrag_server.py (Use llm_binding_api_key for OpenAI alike LLM)
- Added OpenAI alike example in .env.example
- Updated README for LightRAG server

Update OpenAI alike LLM API key handling in lightrag_server

---

lightrag/llm.py

Hi,
Sorry. I just found out that passing the headers to the ollama and lollms directly from llm has a conflict with another header generated inside this so we need to rewrite it.
To fix the problem I just removed the header asignment temporarily and I'll rewrite it this evening.
I tested it last night but it seems that I wasn't testing the right version (my bad)
Sorry for the error. This should fix it.
Have a nice day

Temporary fix to introduced problem in ollama and lollm

---

Dockerfile

To fix docker build failure, add rust toolchain
When we build container, it'll fail due to a lack of rust toolchain.
```
[+] Building 21.0s (10/17)                                                                                docker:desktop-linux
=> [internal] load build definition from Dockerfile                                                                      0.0s
=> => transferring dockerfile: 1.07kB                                                                                    0.0s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)                                            0.0s
=> [internal] load metadata for docker.io/library/python:3.11-slim                                                       0.8s
=> [internal] load .dockerignore …
```

Fix: docker build 

---

lightrag/api/lightrag_server.py

LightRAG support `llm_binding.azure_openai` but due to incorrect condition, we cant use AzureOpenAI currently.
This PR fix it.

add "azure_openai" in llm_binding and embedding_binding

---

lightrag/kg/oracle_impl.py

In the query for `node_degree`, there was a typo that did not match the workspace of the edges, but only of the nodes. The condition `a.workspace = :workspace` was therefore checked twice.

Fixed workspace matching in oracle_impl.py

---

lightrag/api/lightrag_server.py
lightrag/operate.py

Fixing broken main branch:
* Fix LLM binding variable name in create_app function。Corrected variable name from llm_binding_host Updated conditional checks for LLM bindings。
* Add conversation history to naive_query prompt
* Add logging for high and low-level keywords

Fix broken main

---

lightrag/api/static/index.html

this PR fixes auth of webui.
`X-API-Key`: `api-key`   (without Bearer)
is expected form of apikey auth

Fix: WebUI Auth

---

examples/lightrag_zhipu_postgres_demo.py

This PR fix the module import bugs in the [Postgres Demo](https://github.com/HKUDS/LightRAG/blob/main/examples/lightrag_zhipu_postgres_demo.py#L9)
```python
from lightrag.llm.zhipu import ollama_embedding, zhipu_complete
from lightrag.utils import EmbeddingFunc
```
Here `ollama_embedding` should be imported from `lightrag.llm.ollama`.

Fix Module Import Bug of PostgresSQL Demo

---

lightrag/api/README.md
lightrag/api/lightrag_server.py

Add "/bypass" query prefix skip context retrieval from LightRAG, and pass the query directly the underlying  LLM.

Add query prefix "/bypass" for ollama api

---

lightrag/kg/postgres_impl.py

The get_by_id function returns an empty array

Fix get_by_id DB query ressult is empty array

---

lightrag/kg/mongo_impl.py

This change fixes two minor issues in `lightrag/kg/mongo_impl.py`:
1. **Numpy Import Correction**  
- Changed `import np` to `import numpy as np` to fix the module import error.
2. **Motor Dependency Handling**  
- Added a check to install the `motor` package if it's not already installed, ensuring asynchronous MongoDB operations work correctly.

fix mongo impl

---

lightrag/api/lightrag_server.py
lightrag/api/ollama_api.py

Extract the Ollama API related code from the lightrag_server.py file and place it in a separate new file for management. The purposes of doing this are:
- Reduce the size and complexity of the main file (lightrag_server.py)
- Improve code maintainability

Split ollama api to separated file

---

lightrag/api/lightrag_server.py
lightrag/llm/ollama.py
lightrag/llm/openai.py
test_lightrag_ollama_chat.py

- Check if LLM response with None value, and retry if necessary.
- Add error logs for each retry.
- Send 'done' status to client when streaming cancel before finish in Ollama API.
- Improve timing accuracy for Ollama API
- Increase timeout value for unit test.
- Refactor concurrent unit test.

Improve error handling

---

lightrag/api/lightrag_server.py
lightrag/api/ollama_api.py
lightrag/kg/mongo_impl.py
lightrag/kg/oracle_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py

This PR introduces a namespace prefix to storage namespaces to allow different LightRAG to connect to the same database instance while ensuring that the data remains isolated. The changes include:
- Added a namespace_prefix argument to the LightRAG class and associated configurations.
- Updated all storage namespace references to include the prefix.
- Modified the storage implementations (MongoDB, Oracle, PostgreSQL, TiDB) to handle prefixed namespaces.

 add namespace prefix to storage namespaces

---

lightrag/api/lightrag_server.py
lightrag/base.py
lightrag/kg/mongo_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/qdrant_impl.py
lightrag/lightrag.py

This merge request introduces a new `MongoDocStatusStorage` class for managing document processing statuses using MongoDB. It also includes several improvements and fixes:
*   **MongoDocStatusStorage Implementation:** Implements a dedicated storage class for document statuses using MongoDB. This allows for efficient tracking of document states (PENDING, PROCESSING, PROCESSED, FAILED) and associated metadata.
*   **Configuration:** Updates the API server configuration to utilize `MongoDocStatusStorage` when MongoDB is enabled.
*   **Interface Implementation:** Implements the abstract methods (`get_processing_docs`, `get_processed_docs`) defined in the `DocStatusStorage` base class for the PostgreSQL implementation.
*   **Fix MongoKVStorage filter_keys Type Error:** Corrects a type error in …

add MongoDocStatusStorage

---

lightrag/api/lightrag_server.py
lightrag/kg/neo4j_impl.py

When `MAX_CONNECTION_POOL_SIZE` is specified in `.env`, the value of 
```python
MAX_CONNECTION_POOL_SIZE = os.environ.get("NEO4J_MAX_CONNECTION_POOL_SIZE", 800)
```
will be a string, which will cause an error in:
```python
infinite_pool_size = max_pool_size < 0 or max_pool_size == float("inf")
```

fix: neo4j MAX_CONNECTION_POOL_SIZE impl

---

lightrag/api/lightrag_server.py
lightrag/lightrag.py

Move document scanning trigger by command line to background task
- Added background document scanning task to lifespan if needed
- Refactor file conversion to use async execution to prevent blocking event loop of FASTAPI
- Maintain same functionality as before

Move document scanning trigger by command line to background task

---

lightrag/api/lightrag_server.py

This pull request fixes a bug that occurs when using Azure OpenAI through the  [LiteLLM](https://github.com/BerriAI/litellm) 
proxy to manage and track the api calls. The issue arises because the embedding_binding_host was not being properly specified, causing the system to default to OpenAI's API endpoint instead of routing requests through LiteLLM.
- Updated the  openai_embed  call to explicitly use embedding_binding_host when LiteLLM is used as a proxy.
- Ensured that args.embedding_binding_host is correctly propagated and used when configuring the embedding function.
Confirmed the fix allows embedding requests to route through LiteLLM instead of OpenAI default binding host
Without this fix:
- Requests intended to use Azure OpenAI through LiteLLM would default to the OpenAI endpoint …

Enable LiteLLM proxy with embedding_binding_host

---

lightrag/api/README.md
lightrag/kg/mongo_impl.py
lightrag/lightrag.py
lightrag/types.py
lightrag_webui/src/components/PropertiesView.tsx
lightrag_webui/src/hooks/useLightragGraph.tsx
lightrag_webui/src/stores/graph.ts

This Pull Request introduces MongoDB VectorDB support and optimizes existing MongoDB implementations for KV, Doc Status, and Graph storage within LightRAG.
*   **MongoVectorDBStorage (New):** Implements vector data storage and provides similarity search capabilities using Atlas Vector Search. The MongoDB VectorDB implementation was contributed by @ankit1063 in issue #672.
*   **MongoKVStorage (Optimized):** This PR includes improvements for asynchronous operations.
*   **MongoDocStatusStorage (Optimized):** This PR includes improvements for asynchronous operations.
*   **MongoGraphStorage (Optimized):** This PR includes improvements for graph traversal and asynchronous operations. Adds the ability to retrieve all labels and query knowledge graphs with a specified label and maximum depth. …

Add MongoDB VectorDB Support and Optimize Existing MongoDB Implementations

---

.env.example
lightrag/api/README.md
lightrag/api/lightrag_server.py
lightrag/api/ollama_api.py
lightrag/kg/faiss_impl.py
lightrag/kg/nano_vector_db_impl.py

refactor: improve CORS and streaming response headers
- Add configurable CORS origins from environment variable
- Remove duplicate CORS headers
- Add X-Accel-Buffering header
- Update env example file

improve CORS and streaming response headers

---

lightrag/base.py
lightrag/kg/age_impl.py
lightrag/kg/chroma_impl.py
lightrag/kg/faiss_impl.py
lightrag/kg/gremlin_impl.py
lightrag/kg/json_doc_status_impl.py
lightrag/kg/json_kv_impl.py
lightrag/kg/milvus_impl.py
lightrag/kg/mongo_impl.py
lightrag/kg/nano_vector_db_impl.py
lightrag/kg/neo4j_impl.py
lightrag/kg/networkx_impl.py
lightrag/kg/oracle_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/qdrant_impl.py
lightrag/kg/redis_impl.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py

This pull request enhances the proper implementation of subclasses by improving abstract base classes (ABCs) and enforcing method consistency.
Key Changes:
- Added ABC inheritance and `@abstractmethod` decorators where necessary to ensure proper enforcement of method implementation.
- Ensured all base class methods are properly implemented in subclasses, preventing missing abstract methods and making the codebase more robust.
- Many methods are still missing, but we can see where now.
- This ensures that if a method is added to the base class, it must be implemented across all subclasses.
- Standardized method signatures across different storage classes to improve consistency and maintainability.
- Implemented missing methods in subclasses to align with the base class structure.
- Added …

Enhancing ABC Enforcement and Standardizing Subclass Implementations

---

README.md

Edited examples to use ```from lightrag.lightrag import LightRAG, QueryParam``` instead of ```from lightrag import LightRAG, QueryParam``` (latter causes Unresolved reference error upon pip install of LightRAG v1.1.6)

Update README.md - Imports

---

examples/lightrag_api_oracle_demo.py
examples/lightrag_oracle_demo.py
examples/lightrag_tidb_demo.py
examples/lightrag_zhipu_postgres_demo.py
lightrag/api/lightrag_server.py
lightrag/base.py
lightrag/kg/mongo_impl.py
lightrag/kg/oracle_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py

This PR refactors the database connection management for PostgreSQL, Oracle, and TiDB by introducing a `ClientManager` class. It also enhances the lifecycle management of storage components in `LightRAG`, ensuring consistency and better maintainability.
1. **Unified Database Initialization for All Backends:**
- Previously, PostgreSQL, Oracle, and TiDB could not be automatically created and configured like other backends when used outside the `lightrag_server` environment. This update ensures that all backends now exhibit consistent behavior.
2. **Decoupled Backend Implementations from `lightrag_server`:**
- Previously, `lightrag_server` explicitly imported and initialized PostgreSQL, Oracle, and TiDB, which increased backend maintenance complexity and violated the principle of backend …

Refactor Database Connection Management and Improve Storage Lifecycle Handling

---

lightrag/api/lightrag_server.py
lightrag/lightrag.py

- Fix docx pptx indexing error
- Add xlsx support

Fix office file indexing problem

---

README.md
examples/insert_custom_kg.py
lightrag/lightrag.py

Fix for #745 
Custom knowledge graph insertion fails due to required properties not provided (tokens, chunk_order_id, full_doc_id, status).

Fixed broken ainsert_custom_kg()

---

lightrag/kg/neo4j_impl.py
lightrag/kg/networkx_impl.py

This PR addresses an issue where an ImportError for the networkx library was incorrectly raised due to a try-except block that masked the real problem. The actual issue was a ModuleNotFoundError for the past module, which is part of the future package.
Since pipmaster is used to verify that the module is already installed, no need to use that extra try except especially that it hides the real error.
This fixes issue: #871

Fix ImportError by Removing Redundant Try-Except Block

---

lightrag/api/lightrag_server.py
lightrag/base.py
lightrag/kg/age_impl.py
lightrag/kg/gremlin_impl.py
lightrag/kg/mongo_impl.py
lightrag/kg/neo4j_impl.py
lightrag/kg/networkx_impl.py
lightrag/kg/oracle_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py
lightrag/tools/lightrag_visualizer/graph_visualizer.py

- Remove unsused method
- Cleaned get_all_labels never implemented everywhere
- Cleaned import
- Info print
- Remove get_all_labels

Cleanup of code

---

README.md
lightrag/lightrag.py

Add possibility to provide IDs to `insert` and `ainsert` methods of LightRAG.
+
Fixed issue in `apipeline_process_enqueue_documents` method, which was using `compute_mdhash_id` function once again to generate id, instead of using existing one.
* https://github.com/HKUDS/LightRAG/issues/661
* https://github.com/HKUDS/LightRAG/pull/758
* add optional ids param (`listr[str]`) to `insert`, `ainsert` and `apipeline_enqueue_documents`.
* If param is not provided, generate ids using `compute_mdhash_id` function - as before.
* deduplicate based on document content - content is now value in dictionary `contents`.
* use `doc_id` in `apipeline_process_enqueue_documents`
Hi there,
I saw [closed PR about it](https://github.com/HKUDS/LightRAG/pull/758/commits), but I wanted this change, so I decided to …

add support of providing ids for documents insert

---

lightrag/lightrag.py

fix insert_custom_chunks skipping every new doc and throwing warning "This document is already in the storage."
Bug fix. set(doc_key) was creating a set of letters {a,b,c,...} instead of putting doc_key into a set as a single element.
set(doc_key) -> {doc_key}

fix insert_custom_chunks skipping every new doc

---

lightrag/lightrag.py

This PR fixes a missing argument issue in `apipeline_enqueue_documents` by making the `ids` parameter optional. If `ids` is not provided, the function now automatically generates unique MD5-based document IDs. This prevents runtime errors when the function is called without explicit IDs. 
I tested it with neo4j as backend system for graph db
- Fixes missing argument errors in API calls such as `pipeline_index_texts`.
- Ensures backward compatibility while improving robustness.
Error received without fix:
```bash
lightrag    | INFO:     172.25.0.1:54700 - "POST /documents/upload HTTP/1.1" 200 OK
lightrag    | ERROR:Error processing or enqueueing file testfile.md: LightRAG.apipeline_enqueue_documents() missing 1 required positional argument: 'ids'
lightrag    | ERROR:Traceback (most recent …
```

fix apipeline_enqueue_documents

---

lightrag/api/routers/graph_routes.py
lightrag/kg/networkx_impl.py
lightrag/lightrag.py

Implement Knowledge Graph API for Networkx Storage
- Implement Knowledge Graph API for Networkx Storage
- Limit max graph size to 500 nodes to avoid fontend performance issue
- Set the max depth of grapht search to 3

Implement Knowledge Graph API for NetworkX Storage

---

lightrag/llm/hf.py

Running lightrag_hf_demo with nomic-embed-text raises `AttributeError: 'NoneType' object has no attribute 'dim'`. version: 1.2.1
```
File "/Users/konradwojciechowski/PyCharmProjects/graph-rag/LightRAG/lightrag/lightrag.py", line 982, in query
return loop.run_until_complete(self.aquery(query, param, system_prompt))  # type: ignore
File "/Users/konradwojciechowski/.pyenv/versions/3.10.16/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/Users/konradwojciechowski/PyCharmProjects/graph-rag/LightRAG/lightrag/lightrag.py", line 1023, in aquery
response = await naive_query(
File "/Users/konradwojciechowski/PyCharmProjects/graph-rag/LightRAG/lightrag/operate.py", line 1564, in naive_query
results = await chunks_vdb.query(query, …
```

fix AttributeError: 'NoneType' object has no attribute 'dim'

---

lightrag/lightrag.py

This pull request improves the asynchronous management of storage initialization and finalization in the LightRAG class.
It introduces the _run_async_safely() method to handle asynchronous execution safely, preventing event loop conflicts.
Storage initialization is now automatically managed upon object creation (self.initialize_storages).
Storage finalization is triggered when the object is deleted (self.finalize_storages).
This PR addresses potential issues with event loop conflicts when running asynchronous functions within synchronous contexts.
Added _run_async_safely() method to execute async functions safely without blocking the event loop.
Ensured that storage initialization (initialize_storages) runs when auto_manage_storages_states is enabled.
Automatically finalizes storage …

fix this event loop is already running

---

lightrag/lightrag.py

1. Support the single str of the document ids as Lightrag support the single document string in the `insert` method
2. Support predefine the document id for `insert_custom_chunks` method 
Enhance the https://github.com/HKUDS/LightRAG/pull/892
Same as the description.

add support for the single document and custom chunks method

---

lightrag/lightrag.py
lightrag/operate.py

This update fixes the `delete_by_document_id` function, ensuring that deleted data is properly removed from the database and entity relationships are updated accordingly. However, the deletion process does not take effect in real-time due to caching. A service restart is required to apply the new data flow and fully remove the deleted data.  
[Issue](https://github.com/HKUDS/LightRAG/issues/926)
- Implemented logic to delete documents from the database using `document_id`.  
- Updated entity relationships to reflect the deletion.  
- Currently, deleted data is successfully removed from the database, but due to caching, the changes are not immediately reflected.  
- A service restart is required to apply the updated data flow and ensure the removed data is no longer accessible.  
- Future …

feat: fix delete by document id

---

lightrag/lightrag.py

In certain use cases we would like to provide a full doc_id instead of using the source id
Added an optional parameter to the insert function of the LightRAG

adding full_doc_id to insert

---

MANIFEST.in
lightrag/api/lightrag_server.py

Missing MANIFEST.in file for API Server installation, cause webui can not be access for non-debug installation.
- Added MANIFEST.in to include webui files
- Removed /webui/ endpoint from lightrag_server.py

fix: api server installation missing MANIFEST.in file

---

env.example
lightrag/api/lightrag_server.py
lightrag/api/utils_api.py

The language was not considered when using lightRAG_server. Even though the variable SUMMARY_LANGUAGE was defined in the env.example, it was not used anywhere.
I fixed that.

[EVO] Add language configuration to environment and argument parsing

---

lightrag/kg/qdrant_impl.py

Qdrant now is using `PointStruct.payload["id"]`, not `PointStruct.id` UUID. This will fix id overwrite
```python
async def initialize_rag():
rag = LightRAG(
working_dir=WORKING_DIR,
embedding_func=azure_openai_embed,
llm_model_func=azure_openai_complete,
kv_storage="RedisKVStorage",
graph_storage="Neo4JStorage",
vector_storage="QdrantVectorDBStorage", # Milvus is ok
doc_status_storage="MongoDocStatusStorage",
)
await rag.initialize_storages()
await initialize_pipeline_status()
return rag
def main():
rag = asyncio.run(initialize_rag())
with open(os.path.join(ROOT_DIR, "some.md"), "r", encoding="utf-8") as f:
rag.insert(f.read())
print("naive search")
print(
rag.query(
"请用中文回答: 介绍下向量内积?", param=QueryParam(mode="naive")
)
)
```
When using `QdrantVectorDBStorage`, it errors:
```text
No valid …
```

Fix qdrant payload id

---

lightrag/api/lightrag_server.py
lightrag/api/utils_api.py
lightrag/kg/json_doc_status_impl.py
lightrag/kg/json_kv_impl.py
lightrag/kg/neo4j_impl.py
lightrag/kg/shared_storage.py
lightrag/lightrag.py
lightrag/operate.py
lightrag/utils.py

Refactoring Neo4j implementation and fixing storage cache handling problem.
- Fix duplicate nodes for same entity(label)  problem in Neo4j, by adding entity_id field as the key of node in Neo4j. Update MERGE query to use entity_id as key
- Change Neo4j graph relationships to undirected.
- Close Neo4j DB session properly and ensure all result is consumed
- Reduce the connection pool size from 800 to 50
- Suppress no lablel warning from DBMS
- 
- Add async lock for atomic graph database operations, ensured atomic node/edge merge and insert operation
- Fix async namespace init problem for Gunicorn startup mode
- Fix KV storage persistance problem for LLM cache
- Unified llm_response_cache and hashing_kv, prevent creating new storage instance for hashing_kv
- Added update flag to avoid …

Refactoring Neo4j implementation and fixing storage init problem for Gunicorn

---

lightrag/llm/azure_openai.py

Specify `azure_deployment` parameter when calling Azure OpenAI service. This parameter is mandatory; otherwise, the constructed URL will not function correctly due to the underlying logic in the `AsyncAzureOpenAI` constructor.
```python
if azure_deployment is not None:
base_url = f"{azure_endpoint.rstrip('/')}/openai/deployments/{azure_deployment}"
else:
base_url = f"{azure_endpoint.rstrip('/')}/openai"
```
I have not see the exact errors in #680, but this fix might be useful for others.
Specify azure_deployment parameter when calling Azure OpenAI service.

Resolve the issue with making API calls to Azure OpenAI service

---

lightrag/lightrag.py

Fixed a bug where merging nodes in Neo4j as a graph database caused all nodes to be deleted when a merged node had the same name as one of the pre-merged nodes.
Merging nodes in Neo4j as a graph database caused all nodes to be deleted when a merged node had the same name as one of the pre-merged nodes.
Skipped deleting nodes with duplicate names during the deletion process.
N/A

Fix the merge bug with Neo4j

---

lightrag/api/lightrag_server.py
lightrag_webui/vite.config.ts

Make backend support frontend local proxy for dev mod
- Set OpenAPI schema URL to `/openapi.json`
- Set docs URL to `/docs`
- Set redoc URL to `/redoc`
- Update Vite config for API docs routing
- Ensure proper path handling for docs endpoints

Explicitly set API docs and schema URLs.

---

lightrag/llm/openai.py

```
async def initialize_rag():
rag = LightRAG(
working_dir="yanbao",
llm_model_func=llm_model_func,
embedding_func=EmbeddingFunc(
embedding_dim=1536,
max_token_size=8192,
func=embedding_func
),
llm_model_kwargs={"stream": True}
)
await rag.initialize_storages()
await initialize_pipeline_status()
return rag
```
If I add the configuration llm_model_kwargs={"stream": True}, the following error occurs.
```
ERROR: Error in get_kg_context: expected string or bytes-like object
```
Perhaps I should not use the stream mode?
my code might not be correct, and I would greatly appreciate any guidance you can provide."

fix stream

---

lightrag/kg/postgres_impl.py

The chunk_id's appends every time a the relation or entity is detected, this will eventual lead to the VARCHAR(255) field to throw an overflow error.
- https://github.com/HKUDS/LightRAG/issues/1088
- Changed chunk_id's VARCHAR(255) fields to a TEXT field

Updated PSQL's chunk_id field to be a TEXT field

---

lightrag/lightrag.py

- Process batch one by one
- Process documents in parallel within each batch
The previous implementation is the opposite. That is why files is process one by one in all files fit in one batch.

Fix pipeline bactch process problem

---

lightrag/operate.py

Fixed a bug in the entity extraction process where placeholder variables in the `continue_prompt` were not being properly formatted with context values, potentially causing incorrect entity extraction results.
Addresses an issue where entity extraction might fail or produce unexpected results due to unformatted placeholders in prompts.
Modified the `extract_entities` function to properly format the `continue_prompt` with the context_base dictionary, ensuring all placeholders like {entity_types}, {tuple_delimiter}, etc. are correctly replaced with their actual values.
N/A

fix continue prompt format error

---

lightrag/kg/postgres_impl.py
lightrag/lightrag.py

The baseclass 'DocStatusStorage' enforces the 'get_by_id' method to return a dict. However, the postgres implementation of that class returns a dataclass, which behaves differently.
- Changed return value from 'DocProcessingStatus' dataclass to a dict
- Some minor 'leave the place better behind' fixes
I like the idea of returning an explicit type, rather than a dict. But since all the other implementations of 'DocStatusStorage' return a dict, I think we should adhere to the contract for now.

Fixed get_by_id type error in PSQL impl

---

lightrag/kg/postgres_impl.py

1. #1085 introduced that  chunk_ids of LIGHTRAG_VDB_ENTITY and LIGHTRAG_VDB_RELATION should be an array of VARCHAR.
2.  remove incorrect filepath type conversion.
#1113 
This pr has already tested by [lightrag_zhipu_postgres_demo.py](https://github.com/HKUDS/LightRAG/blob/main/examples/lightrag_zhipu_postgres_demo.py) locally.

fix: correct chunk_ids as array type and remove incorrect filepath type conversion

---

lightrag/api/auth.py
lightrag/api/gunicorn_config.py
lightrag/api/lightrag_server.py
lightrag/api/routers/document_routes.py
lightrag/api/run_with_gunicorn.py
lightrag/api/utils_api.py
lightrag/kg/shared_storage.py

Optimize parallel file processing in folder scan and fix dead lock problem in Gunicorn multi workers mode
n/a
- Enqueue files to pipeline batch by batch to utilize parallel documents processing ability of the index stage
- Changed parallel enqueue  to sequential to prevent CPU overload by heavy file extraction jobs
- Resolve dead lock problem which occur in parallel documents processing with Gunicorn mode
- Prioritize OS environment variables over .env file to improve Docker compatibility for the server
- Increased default timeout values for Gunicorn configuration

Optimize parallel file processing in folder scan and fix dead lock problem in Gunicorn multi workers mode

---

env.example
lightrag/api/README.md
lightrag/kg/mongo_impl.py

The MongoDocStatusStorage's get_docs_by_status() method constructs DocProcessingStatus without required `file_path` attribute, this will cause error when insert documents into lightrag.
#843 
Add the missing file_path attribute and use `_id` as default value.
```python
async def get_docs_by_status(
self, status: DocStatus
) -> dict[str, DocProcessingStatus]:
"""Get all documents with a specific status"""
cursor = self._data.find({"status": status.value})
result = await cursor.to_list()
return {
doc["_id"]: DocProcessingStatus(
content=doc["content"],
content_summary=doc.get("content_summary"),
content_length=doc["content_length"],
status=doc["status"],
created_at=doc.get("created_at"),
updated_at=doc.get("updated_at"),
chunks_count=doc.get("chunks_count", -1), …
```

Fix mongo doc status

---

README.md

README.md seems to have a missed close </div>, causing the entire page to get centered -- it makes the code examples especially hard to read :)

Un-center README.md

---

lightrag/api/lightrag_server.py
lightrag/api/run_with_gunicorn.py

This PR enhances environment variable handling to support running multiple instances of LightRAG simultaneously.
- Added support for using the `.env` file from the execution folder by default
This enables a powerful workflow where users can:
1. Create separate folders, each containing:
- A custom `.env` configuration file
- An `inputs` folder for instance-specific data
- Run multiple LightRAG instances (datalates) in parallel
- Configure each instance independently with different:
- LLM models
- Embedding models
- Port numbers
- OLLAMA simulated service names
- Other environment-specific settings
Simply create a new folder structure, add your custom `.env` file, and launch the LightRAG server from that location.

upgraded to use current folder's .env if present

---

lightrag/api/auth.py
lightrag/api/lightrag_server.py
lightrag/api/run_with_gunicorn.py
lightrag/api/utils_api.py
lightrag/utils.py

refactor: standardize .env loading behavior across modules
- Use .env from current folder for each lightrag instance
- Allow different .env files for different instances
- Make OS env vars take precedence over .env file

Refactor: Standardize .env loading behavior across modules

---

env.example
lightrag/api/README.md

Remove the comments at the end of the environment variable lines in .env file

Remove the comments at the end of the environment variable lines in .env file

---

lightrag_webui/src/hooks/useLightragGraph.tsx

At present, all edge labels display the hard coded 'Directed', and it is unclear how they were designed and considered. Do you feel like changing it to properties Keywords are more meaningful？
Also, can we associate the weights of edge with their thickness? If so, I will develop this area

fix(useLightragGraph): Change the label of the edge from type to keyword

---

lightrag/operate.py

A quickfix for missing file_type key from the query results. Reading [LarFii](https://github.com/LarFii)'s comment, this might be solved later 'https://github.com/HKUDS/LightRAG/issues/1227#issuecomment-2763338486'. But this will make sure the PSQL implementation works for querying in the meantime.
- https://github.com/HKUDS/LightRAG/issues/1227
- Prevented query from failing when the database does not have the file_path column (yet)

Quick Fix: unknown filepath errors

---

lightrag/kg/postgres_impl.py

Added 'file_path' to both get_by_id queries of the postgresql implementation, since they were still missing, which caused the new citation feature to not work when using postgres (and furthermore causes crashes when trying to query).
There is also another fix currently in PR, which adds at least a failsafe in case of doubt when not finding file paths. This fix provides the file paths when using postgres
Related to PR #1264 
Fixes the same problem (at least partially since it would still crash if file_path is empty), but also adds support for acutally getting the file_paths
- Modified postgres_impl.py and added 'file_path' to both get_by_id queries
No futher notes since all was covered in the previous texts

fix(postgres_impl): added file_path to queries

---

lightrag/api/routers/ollama_api.py

When you use LightRAG as an Ollama module and prepend your message with /context, LightRAG now will return only the knowledge and documents, without processing them through LLMs.
Add /context query prefix to Ollama model simulation for LightRAG Server #1287
[[Reference any related issues or tasks addressed by this pull request.]](https://github.com/HKUDS/LightRAG/issues/1287)
ollama_api.py:
A /context mode has been added. Knowledge is extracted in hybrid mode (because I didn't make changes to other files, and they are not compatible with context mode).

Add /context query prefix to Ollama model simulation for LightRAG Server

---

lightrag/operate.py
lightrag/utils.py

Recently when I'm testing LightRAG with neo4j, an error occurred like this:
```text
[ERROR][2025-04-07 16:29:24] Traceback (most recent call last):
File "/home/admin/LightRAG/lightrag/api/routers/query_routes.py", line 193, in query_text_stream
response = await rag.aquery(request.query, param=param)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/admin/LightRAG/lightrag/lightrag.py", line 1353, in aquery
response = await kg_query(
^^^^^^^^^^^^^^^
File "/home/admin/LightRAG/lightrag/operate.py", line 749, in kg_query
context = await _build_query_context(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/admin/LightRAG/lightrag/operate.py", line 1144, in _build_query_context
entities_context, relations_context, text_units_context = await _get_edge_data(
^^^^^^^^^^^^^^^^^^^^^
File …
```

Fixed null value handling and ensure exceptions are avoided

---

lightrag/api/run_with_gunicorn.py

I received this error message `Error: unsupported operand type(s) for *: 'NoneType' and 'int'` when running `lightrag-gunicorn`.
I made some small changes to ensure when `global_args.timeout` is `None`, it will not participate in any not-supported operations.

fix error when running caused by `global_args.timeout` being None

---

lightrag_webui/src/features/RetrievalTesting.tsx

History_turns in webui is not effective

fix(RetrievalTesting): Limit the length of conversation history records

---

docker-compose.yml
lightrag/base.py
lightrag/kg/neo4j_impl.py
lightrag/operate.py

Here i added all the "_batch" functions to the neo4j graph db storage as discussed in the issue #1246 
#1246 This issue was about how the graph db was querried multiple thousands of times because of asyncio.gather instead of batching the strings and sending one big list[str] and getting one big answer back.
I made changes to operate.py to no longer call the functions one by one but first create a list and then send it once. 
I made changes to base.py to include the new functions. 
I made changes to neo4j_impl.py to include the new functions 
And finally i added neo4j to the dockercompose so it might be a bit easier to test. But this change can ofcourse be removed.
- [Done] Changes tested locally
I would assume that this is a small change within a bigger picture. All graph db should be …

Neo4j batching with UNWIND on get_node, get_edge, node_degree, edge_degree, get_node_edges

---

lightrag/lightrag.py

When using the current `ainsert_custom_chunks` API, an error occurs with `self.chunks_vdb.upsert`. Specifically, during the execution of `PGKVStorage._upsert_chunks`, the fields `tokens`, `chunk_order_index`, and `file_path` are missing, which causes the insertion of custom chunks to fail.
This bug is similar to #745 
Add miss key for ainsert_custom_chunks

fix: add miss key for ainsert_custom_chunks

---

lightrag/kg/postgres_impl.py

A method to retrieve all data has been added to the PGKVStorage class.
#1109 
add get_all()

feat: PGKVStorage add get_all()

---

lightrag/kg/postgres_impl.py

Switched Postgres vector‐store “query” logic to bind document IDs as a proper text[] parameter instead of interpolating a comma‐separated string. This prevents SQL syntax errors when multiple IDs are passed into the CTE (i.e. “syntax error at or near ‘,’”).
* In `lightrag/kg/postgres_impl.py`, refactored the `query(...)` method:
* Removed inline concatenation/quoting of `ids`.
* Always bind `ids` as the second parameter (`$2::varchar[]`) to the SQL.
* Updated the `params` dict to include `"doc_ids": ids`.
* Updated the three RAG SQL templates (“chunks”, “entities”, “relationships”) so their CTEs use:  WHERE $2::varchar[] IS NULL OR full_doc_id = ANY($2::varchar[]) and bumped the downstream placeholders (`$3`, `$4`) accordingly.
* Retained inline formatting of the embedding vector, but no …

use a single parameter placeholder for the array;

---

lightrag/operate.py
lightrag/utils.py

friendly implementation of entity extraction and relationship weight extract for Low-Capability LLMs
This PR addresses two critical issues when processing output from smaller LLMs:
1. These models often produce malformed entity outputs, such as:
- Missing or incorrectly placing record delimiters (e.g., placing them inside parentheses)
- Omitting opening or closing parentheses.
- Since the current entity extraction logic relies on regex, these issues lead to many valid entities being ignored, resulting in a low entity count.
2. Relationship weights are sometimes returned wrapped in quotes (e.g., "1.0" or '0.8'). The current regex does not handle this properly and defaults to returning a weight of 1.0.
1. Introduces a `new extract_fixed_parenthesized_content` function that runs after …

friendly implementation of entity extraction and relationship weight extract for Low-Capability LLMs

---

lightrag/kg/postgres_impl.py

Resolved an issue where string values were being incorrectly parsed as JSON in PostgreSQL AGE graph storage, which caused errors when processing node names containing JSON-formatted text.

Fix node names with JSON formatting were mistakenly interpreted as JSON objects for PostgreSQL AGE graph storage

---

examples/lightrag_tongyi_openai_demo.py

LightRAG works well with qwen3
Adding Tongyi OpenAI demo to use Qwen model. 
Tongyi also known as Dashscope is Alibaba's LLM servicing platform.
I tested the code with qwen-turbo-latest model which is the just published Qwen3, I found that the built KG is much better with Qwen3 than Qwen2.5 for the same dataset. 
add sample .env config
add examples/lightrag_tongyi_openai_demo.py file

Adding Tongyi OpenAI demo to use Qwen model

---

lightrag/api/config.py
lightrag/api/gunicorn_config.py
lightrag/api/lightrag_server.py
lightrag/api/run_with_gunicorn.py
lightrag/api/utils_api.py
lightrag/constants.py
lightrag/lightrag.py
lightrag/utils.py

This commit introduces `lightrag/constants.py` to centralize default values for various configurations across the API and core components.
Key changes:
- Added `constants.py` to centralize default values
- Improved the `get_env_value` function in `api/config.py` to correctly handle string "None" as a None value and to catch `TypeError` during value conversion.
- Updated the default `SUMMARY_LANGUAGE` to "English"
- Set default `WORKERS` to 2

feat: Centralize configuration and update defaults

---

lightrag/api/__init__.py
lightrag/lightrag.py
lightrag/operate.py

Eliminate redundant chunk data fetching in naive and mix query mode. Use chunks fetched from vector db.
reslove #1535

Eliminate redundant chunk data fetching in naive and mix query mode

---

config.ini.example
lightrag/kg/postgres_impl.py

This PR adds configurable PostgreSQL connection pool size support through both configuration file and environment variables. This enhancement allows users to fine-tune the database connection pool based on their specific needs and system resources.
N/A
1. Added `max_connections` parameter to `config.ini.example` with a default value of 12
2. Modified `PostgreSQLDB` class to read the max connections from config instead of hardcoding it
3. Updated `ClientManager` to support `POSTGRES_MAX_CONNECTIONS` environment variable
This change maintains backward compatibility by:
- Using 12 as the default value if not specified in config
- Supporting both config file and environment variable configuration
- Preserving existing behavior for users who don't specify the parameter
The change allows for …

Allow max_connections to be configured in postgres

---

examples/graph_visual_with_neo4j.py
lightrag/utils.py

This pull request fixes incorrect key mappings in the `xml_to_json` function used to convert GraphML files to JSON. The original mapping between GraphML data keys and node/edge attributes was misaligned, which led to improperly structured JSON output.
To fix this, I moved the `xml_to_json` function from `utils.py` directly into `examples/graph_visual_with_neo4j.py`, and corrected the key assignments for both nodes and edges based on the GraphML schema.
No related issues found in the repository at the time of this PR.
- `entity_type`: from `d0`  to `d1` 
- `description`: from `d1`  to `d2` 
- `source_id`: from `d2`  to `d3` 
- `weight`: from `d3`  to `d5` 
- `description`: from `d4` to `d6` 
- `keywords`: from `d5`  to `d7` 
- `source_id`: from `d6`  to `d8` 
- Moved the `xml_to_json` …

Fix: Correct GraphML to JSON mapping in xml_to_json function

---

lightrag/api/routers/document_routes.py

Adding optional field for text.s requests to support source quoting
#1606 
Updated `document_routes.py`, especially: 
- `InsertTextRequest` classes to take a new field
-  `pipeline_index_texts` to put the sources as file_paths into the rag pipeline.
- [ X] Changes tested locally

Adding file_source.s as optional attribute to text.s requests

---

lightrag/kg/networkx_impl.py

As far as I can tell this is no longer actually used and its usage was removed in this commit: https://github.com/HKUDS/LightRAG/commit/83353ab9a619e921fb71a8b62070acfd6f773b49#diff-a346bcfb05aab0cc0c0baa6018976f4efab339e8cade9f6f8fb658fcbd54ae2e
Our systems are flagging this package as having a dependency on a package with a less permissive license so I would appreciate if it can be removed if its no longer needed.  Let me know if that is not the case.
Removed pip installation of graspologic

Remove graspologic pip installation that no longer seems to be used

---

lightrag/utils_graph.py

Fix `GRAPH_FIELD_SEP` import typo from the wrong module.
#1697
Change import path for `GRAPH_FIELD_SEP` from `prompt.py` to `constants.py` in `utils_graph.py`.

Fix GRAPH_FIELD_SEP import typo

---

lightrag/kg/mongo_impl.py
lightrag/kg/postgres_impl.py

Fix LLM cache handling for MongoKVStorage to address document deletion scenarios.
- Support fetching all "default_" prefixed documents
- Maintain original behavior for other IDs
- Return dictionary of documents for "default"
- Keep backward compatibility

Fix LLM cache handling for MongoKVStorage to address document deletion scenarios

---

lightrag/lightrag.py
lightrag/operate.py

Refac: Add KG rebuild logging with pipeline status
- Logs detailed progress, including warnings and failures, to the pipeline status.
- Adds counters to report the total number of successfully rebuilt entities and relationships upon completion.

Refac: Add KG rebuild logging with pipeline status

---

lightrag/api/__init__.py
lightrag/api/routers/document_routes.py

- Add double-check for pipeline status to prevent race conditions
- Implement automatic processing of pending indexing requests after deletion

Feat: Check pending equest_pending after document deletion

---

lightrag/operate.py

Added validation checks in entity and relationship extraction functions to filter out entities that become empty strings after normalize_extracted_info processing. This prevents empty labels from appearing in get_all_labels() results and maintains knowledge graph data integrity.

fix: prevent empty entity names after normalization in extraction

---

README-zh.md

This pull request fixes a broken link to the Chinese README file in the repository. The original link referenced README_zh.md, which caused a 404 error. It has been corrected to point to the correct file README-zh.md.
N/A
Replaced incorrect reference README_zh.md with README-zh.md in documentation links.
The broken link previously prevented users from accessing the Chinese documentation. This fix ensures the README can be properly opened via browser, improving accessibility for Chinese-speaking users.

Fix incorrect file path (404 Not Found)

---

lightrag/lightrag.py

This pull request addresses a `TypeError` crash that occurs in the document processing pipeline. When a document is submitted as raw text (e.g., via the `/documents/text` API endpoint), the `file_path` attribute is `None`. The existing code did not handle this case and attempted to perform a string slice on the `None` value, causing the background processing task to crash and preventing the document from being indexed.
This change introduces a simple check to handle a `None` `file_path` gracefully by providing a default string, which resolves the crash and ensures that text-based documents can be successfully processed and indexed.
*   This PR fixes a bug that causes a `TypeError: 'NoneType' object is not subscriptable` in `lightrag/lightrag.py` during document processing. While there is …

Fix: Handle NoneType error when processing documents without a file path

---

pyproject.toml

In the changes introduced from tag `1.3.9` to `1.3.10`, the setup of the package was changed from using `setup.py` to using  `pyproject.toml`. Within the pyproject.toml, there's a config error leading to only the `lightrag.api' package being installed.
Installing any version of LightRAG >= 1.3.10 would only install lightrag.api, but not lightrag.kg, lightrag.llm and lightrag.tools.
This would in a regular use case crash the service:
This change makes sure the automatic discovery functionality originally within `setup.py` also works in the `pyproject.toml` file.

fix(build): pyproject.toml setup

---

lightrag/kg/shared_storage.py
lightrag/operate.py

Refactored the KeyedUnifiedLock to be generic and support dynamic namespaces. This decouples the locking mechanism from a specific "GraphDB" implementation, allowing it to be reused across different components and workspaces safely.
Move node existence check inside lock to prevent race condition and prevent duplicate node creation during concurrent updates.
Key changes:
- KeyedUnifiedLock now takes a namespace parameter on lock acquisition.
- Renamed _graph_db_lock_keyed to a more generic _storage_keyed_lock`
- Replaced get_graph_db_lock_keyed with get_storage_keyed_lock` to support namespaces
- Move knowledge_graph_inst.has_node check inside get_storage_keyed_lock
in _merge_edges_then_upsert to ensure atomic check-then-act operations

Refac: Generalize keyed lock with namespace support

---

lightrag/kg/shared_storage.py

- Change cleanup condition from count == 1 to count == 0 to properly remove reused locks from cleanup list
- This prevents locks from being accidentally cleaned up while still in use, resolving "RuntimeError: Attempting to release lock for xxxx more times than it was acquired"

Hotfix: prevent premature lock cleanup in multiprocess mode

---

README-zh.md
README.md
env.example
lightrag/api/README-zh.md
lightrag/api/README.md
lightrag/api/config.py
lightrag/api/lightrag_server.py
lightrag/lightrag.py
lightrag/operate.py

- Refactor the trigger condition for LLM-based summarization of entities and relations rebuild stage after document deletion. Instead of relying on character length, the summary is now triggered when the number of merged description fragments exceeds a configured threshold. This provides a more robust and logical condition for consolidation.
- Introduce the `OLLAMA_NUM_CTX` environment variable to explicitly configure the context window size (`num_ctx`) for Ollama models. This decouples the model's context length from the `MAX_TOKENS` parameter, which is now specifically used to limit input for summary generation, making the configuration clearer and more flexible.
- Updated `README` files, `env.example`, and default values to reflect these changes.

feat: Refine summary logic and add dedicated Ollama num_ctx config

---

README-zh.md
README.md
env.example
lightrag/api/utils_api.py
lightrag/constants.py
lightrag/lightrag.py
lightrag/operate.py

- Remove MAX_TOKEN_SUMMARY parameter and related configurations
- Eliminate forced token-based truncation in entity/relationship descriptions
- Switch to fragment-count based summarization logic using FORCE_LLM_SUMMARY_ON_MERGE
- Update FORCE_LLM_SUMMARY_ON_MERGE default from 6 to 4 for better summarization
- Clean up documentation, environment examples, and API display code
- Preserve backward compatibility by graceful parameter removal
This change resolves issues where LLMs were forcibly truncating entity relationship descriptions mid-sentence, leading to incomplete and potentially inaccurate knowledge graph content. The new approach allows LLMs to generate complete descriptions while still providing summarization when multiple fragments need to be merged.

feat: remove deprecated MAX_TOKEN_SUMMARY parameter to prevent LLM output truncation

---

lightrag/kg/memgraph_impl.py
lightrag/kg/neo4j_impl.py
lightrag/operate.py

- Update extract_entities function in operate.py to use 1.0 as default weight
- Fix Neo4j implementation to use 1.0 instead of 0.0 for missing edge weights
- Fix Memgraph implementation to use 1.0 instead of 0.0 for missing edge weights
- Ensures consistent non-zero default weights across all graph storage backends

fix: change default edge weight from 0.0 to 1.0 in entity extraction and graph storage

---

lightrag/api/routers/ollama_api.py
lightrag/api/routers/query_routes.py

- Update default mode for Ollama chat endpoint
- Update default mode for query endpoint of LightRAG

feat: change default query mode from hybrid to mix

---

lightrag/kg/memgraph_impl.py
lightrag/operate.py

- Implement exponential backoff retry for transaction conflicts
- Add tenacity-based retry decorator with 5 attempts
- Handle TransientError in upsert_node and upsert_edge operations
- Resolve "Cannot resolve conflicting transactions" errors
- Improve system reliability under concurrent load
fix: #1789

Fix: add retry mechanism for Memgraph transient errors

---

lightrag/operate.py

Fix: implemented entity-keyed locks for edge merging operations to ensure robust race condition protection
- Replacing string concatenation with direct list passing for lock keys
- Eliminating deadlock risks by removing the lock around node insertion within the edge merge
- Sort src and tgt for consistent lock keys
- Improve task execution with early failure detection and cancel pending tasks on first exception during merge stage

Fix: implemented entity-keyed locks for edge merging operations to ensure robust race condition protection

---

lightrag/prompt.py

Noticed that during entity extraction the LLM (o4-mini) was making up things under some circumstances for the description. For example given the abbreviation of an organization, the description sometimes contained bogus full name. Ran the original prompt multiple times, and definitely reproducible, LLMs can be pretty creative :)
Extended the instruction to use only the information in the text for the description.
There might be a better prompt, but this seems to be working for me, and wanted to let you know the issue.

Better prompt for entity description extraction to avoid hallucinations

---

lightrag/base.py
lightrag/kg/json_doc_status_impl.py
lightrag/kg/mongo_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/redis_impl.py
lightrag/lightrag.py

feat: separate document content from doc_status to improve performance
This optimization significantly improves doc_status query/update performance by avoiding large string operations during frequent status checks. Remove content field from DocProcessingStatus, and all doc status storage implementation.

Refact remove content in doc status to improve performance 

---

lightrag/kg/postgres_impl.py

fix: Add safe handling for missing file_path and metadata in PostgreSQL doc status functions
- Add null-safe file_path handling with "no-file-path" fallback in get_docs_by_status and get_docs_by_track_id
- Enhance metadata validation to ensure dict type after JSON parsing
- Align PostgreSQL implementation with JSON implementation safety patterns
- Prevent KeyError exceptions when database records have missing fields

fix: Add safe handling for missing file_path in PostgreSQL

---

lightrag/__init__.py
lightrag/api/__init__.py
lightrag/api/config.py
lightrag/base.py
lightrag/lightrag.py

Move OllamaServerInfos class to base module to eliminate dependency of the core module on the API module.
Fixed #1887

Fix: move OllamaServerInfos class to base module

---

env.example
lightrag/llm/binding_options.py

This PR addresses critical issues in the Ollama integration by implementing proper JSON list parameter support, fixing temperature parameter priority logic. This PR significantly improves the robustness and usability of the Ollama integration while maintaining backward compatibility and providing clear migration paths for breaking changes.
The current Ollama integration had several issues:
1. **Incorrect List Parameter Handling**: The `stop` parameter was defined as a string instead of `List[str]`, causing parsing issues with JSON arrays
2. **Temperature Priority Confusion**: Environment variable priority wasn't properly implemented, leading to unexpected behavior when multiple temperature settings were present
3. **Dataclass Field Detection**: The argument parsing system didn't properly …

Fix ollama stop option handling and enhance temperature configuration

---

.gitignore
docker-compose.yml
env.example

- Mount tiktoken cache volume in docker-compose
- Add TIKTOKEN_CACHE_DIR environment variable
- Update env.example with tiktoken cache configuration
- Added /data to gitignore
- Added tiktoken env example

feat: add tiktoken cache directory support for offline deployment

---

env.example
lightrag/kg/postgres_impl.py

This PR introduces support for multiple PostgreSQL vector index types (`IVFFLAT`, `HNSW`, and `FLAT`) for vector-based retrieval in LightRAG.
It:
- Adds index creation logic for the three vector index types
- Enables auto-indexing for three key VDB tables 
- `LIGHTRAG_VDB_CHUNKS`
- `LIGHTRAG_VDB_ENTITY`
- `LIGHTRAG_VDB_RELATION`
- Makes index type configurable via `.env`
- Updates SQL templates to ensure vector indexes are used effectively via `<=>` operator
These enhancements make LightRAG's vector storage more efficient, flexible, and production-ready.
------
Added three async methods for vector index creation:
- `_create_ivfflat_vector_indexes(lists: int = 100)`
- `_create_hnsw_vector_indexes(m: int = 16, ef_construction: int = 256)`
- `_create_flat_vector_indexes()`
Each method …

Add vector index support for PostgreSQL KG

---

lightrag/lightrag.py

- Initialize first_stage_tasks = [] and entity_relation_task = None at coroutine start
- Ensure cancel block safely handles no-op when tasks lists are empty

Fix: Initialize first_stage_tasks and entity_relation_task to prevent empty-task cancel errors

---

env.example
lightrag/operate.py
lightrag/utils.py

Query parameters do not affect keyword extraction structure; therefore, they should be excluded from the cache key.
- Remove query params from cache key generation for keyword extraction
- Remove deprecated return value from handle_cache function.

Fix: remove query params from cache key generation for keyword extraction

---

lightrag/api/routers/document_routes.py
lightrag/lightrag.py

- Check and process enqueued docs even when upload directory is empty
- Persist document data immediately after document is inserted
- Cleanup failed document whit consistency validation, and log the operation to pipeline status for user review

Feat: Reprocessing of failed documents without the original file being present

---

lightrag/api/routers/document_routes.py
lightrag/kg/json_doc_status_impl.py
lightrag/kg/mongo_impl.py
lightrag/kg/redis_impl.py
lightrag/utils.py

Add Chinese pinyin sorting support across document operations
• Replace pyuca with centralized utils function
• Add pinyin sort keys for file paths
• Update MongoDB indexes with zh collation
• Migrate existing indexes for compatibility
• Support Chinese chars in Redis/JSON storage
• Keep PostgreSQL sorting order controled by Database Collate order

Add Chinese pinyin sorting support across document operations

---

lightrag/api/lightrag_server.py

In LightRAG server, If I am using Azure OpenAI for the embeddings or as an LLM, I get the following error when uploading a document:
```
lightrag  | 
lightrag  | LightRAG log file: [REDACTED_PATH]/lightrag.log
lightrag  | 
lightrag  |     ╔══════════════════════════════════════════════════════════════╗
lightrag  |     ║                 LightRAG Server v1.4.7/0207                  ║
lightrag  |     ║         Fast, Lightweight RAG Server Implementation          ║
lightrag  |     ╚══════════════════════════════════════════════════════════════╝
lightrag  |     
lightrag  | 
lightrag  | 📡 Server Configuration:
lightrag  |     ├─ Host: 0.0.0.0
lightrag  |     ├─ Port: 9621
lightrag  |     ├─ Workers: 1
lightrag  |     ├─ Timeout: 150
lightrag  |     ├─ CORS Origins: *
lightrag  |     ├─ SSL …
```

Added import of OpenAILLMOptions when using azure_openai

---

lightrag/operate.py
lightrag/utils.py

This PR significantly improves the text extraction and normalization pipeline in LightRAG by enhancing the `sanitize_and_normalize_extracted_text` function and updating its usage across entity and relationship extraction processes. The changes focus on better handling of quotes, symbols, and edge cases to improve the quality of extracted knowledge graph data.
This enhancement represents a significant improvement to LightRAG's text processing capabilities, making it more robust and suitable for production use with diverse document types and languages.
**Function Signature Update:**
- Changed `sanitize_and_normalize_extracted_text(input_text: str, is_name=False)` to `sanitize_and_normalize_extracted_text(input_text: str, remove_inner_quotes=False)`
- The parameter name change from `is_name` …

refac: Enhanced Entity Relation Extraction Text Sanitization and Normalization

---

lightrag/api/__init__.py
lightrag/operate.py

- Replace <||> with <|>
- Replace < | > with <|>
- Apply fix in both functions
- Handle delimiter variations
- Improve parsing reliability

Fix LLM output instability for <|> tuple delimiter

---

lightrag/kg/networkx_impl.py

- Fix working_dir -> workspace_dir typo
- Correct GraphML file path generation
fix: #2059

Fix incorrect variable name in NetworkXStorage file path

---

lightrag_webui/src/features/GraphViewer.tsx

This PR fixes a dark mode text visibility issue in the knowledge graph view where node and edge labels were rendered in hardcoded black color (#000), making them nearly invisible against the dark background.
Fixes dark mode text visibility in knowledge graph visualization where labels were invisible due to hardcoded black text colors.
- Replace hardcoded black text colors (#000) with dynamic theme-based colors
- Add createSigmaSettings function to generate settings based on theme
- Use labelColorDarkTheme (#B2EBF2) for dark mode and black (#000) for light mode
- Update GraphViewer component to react to theme changes
- Fixes issue where node and edge labels were invisible in dark mode
The fix ensures that both node labels and edge labels properly adapt to the current theme:
- **Light …

fix: resolve dark mode text visibility issue in knowledge graph view

---

lightrag/api/routers/query_routes.py
lightrag/lightrag.py
lightrag/operate.py
lightrag/utils.py

- Add new aquery_llm/query_llm methods providing structured responses
- Consolidate /query and /query/stream endpoints to use unified aquery_llm
- Optimize cache handling by moving cache checks before LLM calls
- Fix logging filter logic and consolidate GET/POST condition logic

Fix double query problem by add aquery_llm function for consistent response handling

---

lightrag_webui/src/components/retrieval/ChatMessage.tsx
lightrag_webui/src/features/RetrievalTesting.tsx

LaTeX formulas displayed red error text during streaming due to KaTeX attempting to parse incomplete formulas, while Mermaid diagrams correctly showed black text during streaming. This created an inconsistent and confusing user experience.
- **Mermaid**: Used `renderAsDiagram` flag to conditionally render as diagram vs. plain text
- **LaTeX**: Always applied KaTeX plugin, causing parsing errors on incomplete formulas during streaming
Implemented LaTeX completeness detection following the same pattern as Mermaid diagrams:
- Extended `MessageWithError` type with `latexRendered?: boolean` field
- Made KaTeX plugin application conditional: `(katexPlugin && (message.latexRendered ?? true))`
```typescript
const detectLatexCompleteness = (content: string): boolean => {
// Check for unclosed …
```

Feat(webui): Prevent LaTeX Parsing Errors During Streaming

---

lightrag/api/routers/document_routes.py
lightrag_webui/src/api/lightrag.ts
lightrag_webui/src/features/DocumentManager.tsx
lightrag_webui/src/locales/en.json
lightrag_webui/src/locales/zh.json

Add a new `/documents/reprocess_failed` API endpoint and corresponding UI button to retry processing of failed and pending documents. This addresses a common recovery scenario when document processing fails due to server crashes, network errors, or LLM service outages.
Backend changes:
- Add ReprocessResponse model with status, message, and track_id fields
- Add POST /documents/reprocess_failed endpoint that triggers background reprocessing of FAILED, PENDING, and interrupted PROCESSING documents
- Reuses existing apipeline_process_enqueue_documents for consistency
- Includes comprehensive docstring and logging for observability
Frontend changes:
- Add TypeScript types and API function for the new endpoint
- Add retry handler with intelligent polling (fast refresh → normal)
- Add "Retry …

feat: Add endpoint and UI to retry failed documents

---

lightrag_webui/src/features/DocumentManager.tsx

• Add track ID to tooltip display
• Remove JSON braces from metadata
• Reorder tooltip content layout
• Clean up metadata indentation
• Show track ID before metadata

Refactor(webui): Improve document tooltip display with track ID and better formatting

---

lightrag/kg/networkx_impl.py

Fixed typo in log message when creating a new graph file.
Before: `Created new empty graph fiel`
After: `Created new empty graph file`

Fixed typo in log message when creating new graph file
