lightrag/lightrag.py
lightrag/llm.py
lightrag/operate.py

Now, We add new function hf_model_complete&hf_embedding to support huggingface model : )

Add HF Support

---

examples/lightrag_openai_compatible_demo.py
lightrag/llm.py

Added base_url, model, and api_key options to make it compatible with all Open AI-like chat/embeddings APIs, including Mistral, Llama, Together.ai, Fireworks, Croq, etc.
It will significantly improve the compatibility and usability of LightRAG.
See `examples/lightrag_openai_compatible_demo.py`.

Added OpenAI compatible options and examples

---

reproduce/Step_1_openai_compatible.py
reproduce/Step_3_openai_compatible.py

update reproduce/Step_3.py slightly
add open ai compatible script for reproduce/Step_1 and Step_2

update Step_3.py and openai compatible script

---

README.md

Add lines that can be uncommented if running in a jupyter notebook

Add comment specifying jupyter req

---

examples/graph_visual.py

Add colors to nodes to make graph visualization look like this:

make graph visualization become colorful

---

lightrag/llm.py

Added a class to use multiple models 

---

examples/lightrag_openai_compatible_demo.py

I fixed the embedding dimension problem which is usually encountered since the defalut setting is 4096, but different embedding modals always have different dimensions. Thus I Implemented automatic detection of the embedding dimension to ensure consistency, preventing issues during the concatenation of embedding arrays. The issue address is [no.75]
https://github.com/HKUDS/LightRAG/issues/75

[hotfix-#75][embedding] Fix the potential embedding problem

---

lightrag/lightrag.py
lightrag/operate.py

typo(lightrag/lightrag.py): typo

---

setup.py

Error Handling:
Handled potential FileNotFoundError for README.md and requirements.txt. Checked for missing required metadata and raised an informative error if any are missing. Automated Package Discovery:
Replaced packages=["lightrag"] with setuptools.find_packages() to automatically find sub-packages and exclude test or documentation directories. Additional Metadata:
Added Development Status in classifiers to indicate a "Beta" release (modify based on the project's maturity). Used project_urls to link documentation, source code, and an issue tracker, which are standard for open-source projects. Compatibility:
Included include_package_data=True to include additional files specified in MANIFEST.in. These changes enhance the readability, reliability, and openness of the code, making it …

Key Enhancements:

---

lightrag/lightrag.py
lightrag/operate.py

fixing knowledge_graph keyword bug

---

examples/lightrag_lmdeploy_demo.py
lightrag/llm.py
requirements.txt

as title, support [lmdeploy](https://github.com/InternLM/lmdeploy/tree/main). `lmdeploy` is commented in requirements.txt as not every gpu support lmdeploy

[Feature]  support lmdeploy backend

---

.gitignore
README.md
examples/lightrag_ollama_demo.py
lightrag/lightrag.py
lightrag/llm.py

This PR contains following improvements:
* More detailed explanation how to work with ollama in README.
* Ready to try ollama example without any additional setup.
* Added ability to pass additional arguments to ollama library like host, timeout etc.

Add ability to pass additional parameters to ollama library 

---

examples/lightrag_openai_compatible_demo.py

I fixed the asynchronous problem. The issue address is [no.163]
#163

[hotfix-#163] Fix asynchronous problem

---

reproduce/Step_3.py

Fix the same bug of Step_3_openai_compatible.py in Step_3.py in reproduce steps

fix:Step_3.py context

---

lightrag/operate.py
lightrag/utils.py

1. Fix the output of "combine_contexts" in "hybrid_query"
2. Fix the combine and deduplication in combine_contexts
3. Modify list_of_list_to_csv
4. Add csv_string_to_list

Fix combine_contexts in hybrid_query

---

README.md
examples/lightrag_api_openai_compatible_demo.py

Function enhancement

---

README.md

add missing imports to examples in README.md

add missing imports to examples in README.md

---

README.md

I am not sure streamlit is the interface I want to contribute back to the LightRAG project, but willing to share it all under the same MIT license. It seemed you did not like streamlit as well. I am working on taipy or flask next and can contribute that how you suggest.
I figured I would at least share the link and source code in the README.
I would like to understand how you benchmark and want to visualize the investigation/verification workflows for future version.

Added GUI (linked), updated README.md

---

lightrag/llm.py

as title. currently local hf model embed func doesn't take care of loading model to cuda.

fix hf embedding to support loading to different device

---

lightrag/kg/oracle_impl.py

I have update the parameter binding type in oracle_impl, so that it can handle some key words appearing in column's content
change:
lightrag/kg/oracle_impl.py

change the type of binding parameters in Oracle23AI

---

examples/lightrag_oracle_demo.py

Add embedding_func for graph database, it's deleted in commit 5661d76860436f7bf5aef2e50d9ee4a59660146c
This will fix oracle database issue.

fix embedding_func issue for oracle database

---

lightrag/llm.py

https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embedding

Ollama `embedding` deprecated in favor of `embed`

---

README.md
lightrag/lightrag.py
test_neo4j.py

fix missing required positional argument and wrong argument name

fix neo4jstorage bug

---

examples/lightrag_ollama_neo4j_milvus_demo.py
lightrag/kg/milvus_impl.py
lightrag/lightrag.py
requirements.txt

Add Milvus as vector storage

---

examples/lightrag_ollama_neo4j_milvus_mongo_demo.py
lightrag/kg/mongo_impl.py
lightrag/lightrag.py
requirements.txt

`examples/lightrag_ollama_neo4j_milvus_demo.py` -> `examples/lightrag_ollama_neo4j_milvus_mongo_demo.py`

Add MongoDB as KV storage

---

examples/graph_visual_with_html.py

Added feature for interactive graph: Mouse hover nodes and edges displays description of the entity/relationship.
Here's the screenshots from the Christmas Carol book:
Mouse hover the entity "Fred"
Mouse hover the relationship "Fred" - "Christmas"

Interactive Graph: Mouse hover nodes and edges displays description in pop-up window

---

lightrag/operate.py

https://github.com/HKUDS/LightRAG/issues/306
主要修改包括：
在存储文本块数据时增加了验证，确保只存储有效的数据
在处理文本块之前增加了空列表检查
在截断文本块之前过滤掉无效的数据
增加了更多的日志警告信息
查询的修改：
添加了对 chunks 的有效性检查,过滤掉无效的 chunks:

修复bug https://github.com/HKUDS/LightRAG/issues/306

---

lightrag/llm.py

simple fix double quote error.

Fix: syntaxError

---

lightrag/lightrag.py
lightrag/llm.py

add lazy_external_load to reduce external lib deps whenever it's not necessary for user.

fix extra kwargs error: keyword_extraction.

---

lightrag/lightrag.py

`is_closed()` is better practice

fix(lightrag): use is_closed() instead of _closed

---

lightrag/prompt.py

提取关键词的prompt优化

---

lightrag/llm.py

chore: update llm.py

---

lightrag/operate.py

fix: fix variable name(entitiy->entity)

---

lightrag/operate.py

1. 避免变量在赋值之前就被引用
2. 解决未找到entity返回None导致的unpack问题

fix: update operate.py

---

api/README_LOLLMS.md
api/lollms_lightrag_server.py
lightrag/llm.py

This PR adds support for LoLLMs (Lord of Large Language Models) as a new LLM backend for LightRAG, expanding the available options beyond Ollama. LoLLMs is a versatile AI framework that supports multiple LLM backends and provides comprehensive text generation and embedding capabilities.
- Added `lollms_model_if_cache` for text generation support
- Added `lollms_model_complete` as a high-level interface
- Added `lollms_embed` for document embedding support
- Full streaming support for text generation
- Compatible with existing LightRAG interfaces
- A fastapi service using lollms as backend
- New async client implementation for LoLLMs server communication
- Support for both streaming and non-streaming text generation
- Embedding generation using LoLLMs' configurable vectorizers (semantic, …

Add LoLLMs Integration to LightRAG

---

lightrag/kg/gremlin_impl.py

Tested on ArcadeDB with Gremlin plugin. The main change is using "entity_name" vertex property instead of the label as a node_id since different implementations have different restrictions on label names.

GremlinStorage: support more Gremlin compatible DBs

---

README.md
lightrag/base.py
lightrag/kg/age_impl.py
lightrag/lightrag.py
lightrag/storage.py

feat(lightrag): Add document status tracking and checkpoint support
功能(lightrag): 添加文档状态跟踪和断点续传支持
- Add DocStatus enum and DocProcessingStatus class for document processing state management
- 添加 DocStatus 枚举和 DocProcessingStatus 类用于文档处理状态管理
- Implement JsonDocStatusStorage for persistent status storage
- 实现 JsonDocStatusStorage 用于持久化状态存储
- Add document-level deduplication in batch processing
- 在批处理中添加文档级别的去重功能
- Add checkpoint support in ainsert method for resumable document processing
- 在 ainsert 方法中添加断点续传支持，实现可恢复的文档处理
- Add status query methods for monitoring processing progress
- 添加状态查询方法用于监控处理进度
- Update LightRAG initialization to support document status tracking
- 更新 LightRAG 初始化以支持文档状态跟踪

功能(lightrag): 添加文档状态跟踪和断点续传支持

---

lightrag/prompt.py

优化mix查询模式的提示词

---

lightrag/operate.py
lightrag/prompt.py
lightrag/storage.py

- 为关系和向量数据增加时间戳支持,记录知识获取的时间
- 优化混合查询策略,同时考虑语义相关性和时间顺序
- 增强提示词模板,指导LLM在处理冲突信息时考虑时间因素

feat: 增强知识图谱关系的时序性支持

---

lightrag/kg/neo4j_impl.py

issue:#535 中提到neo4j_impl中是否能够实现选取指定数据库的功能。事实上，Neo4j Desktop/Enterprise版中是支持创建和切换不同的数据库的功能的。在这里我做了一个简单的实现。

添加选取Neo4j指定数据库功能的支持

---

lightrag/lightrag.py

I implemented a custom insert function by the name 'insert_custom_chunks' where user can create chunks themselves and pass the list of chunks as an input to this function (instead of usual text only)

Implement custom chunking feature

---

lightrag/lightrag.py
lightrag/operate.py

There was no option to pass a custom chunking function dynamically within the LightRAG class. This limitation restricted flexibility when dealing with different chunking requirements for text processing. Introduced a variable `chunking_func` in LightRAG class to accept a custom chunking function. Additional arguments for the custom function can be passed dynamically through `chunking_func_kwargs`. This resolves the issue and ensures the chunking process is adaptable to specific needs.

Add custom chunking function.

---

lightrag/kg/postgres_impl.py
lightrag/kg/postgres_impl_test.py

I found that the AGE implementation, while getting node_edges, it did not decode it. it might impact the query accuracy, now fix it.

Revise the AGE implementation on get_node_edges, to align with Neo4j behavior.

---

lightrag/kg/mongo_impl.py
lightrag/kg/neo4j_impl.py

1. add os env NEO4J_MAX_CONNECTION_POOL_SIZE for neo4j ;
2. fix https://github.com/HKUDS/LightRAG/issues/580 issue for mongoDB document 16MB limit.

Fix for mongoDB document 16MB limit and add os env NEO4J_MAX_CONNECTION_POOL_SIZE for neo4j 

---

lightrag/api/lightrag_server.py
lightrag/api/requirements.txt

This PR adds support for multiple document formats (.pdf, .docx, .pptx) in addition to the existing .txt and .md support. It also introduces dynamic dependency management using pipmaster.
- Added support for PDF, DOCX, and PPTX files
- Implemented dynamic dependency installation using pipmaster
- Enhanced error handling and reporting
- Updated all document-related endpoints
- /documents/scan
- /documents/upload
- /documents/file
- /documents/batch
Dependencies are now installed dynamically when needed:
- pypdf2 (for PDF files)
- python-docx (for DOCX files)
- python-pptx (for PPTX files)
- Updated supported file types in documentation
- Added notes about dynamic dependency installation
- Tested all endpoints with various file formats
- Verified dynamic dependency installation
- Checked …

Enhancement: Multi-format document support and dynamic dependency management #565

---

examples/openai_README_zh.md
lightrag/llm.py

add readme_zh

---

extra/OpenWebuiTool/openwebui_tool.py

The tool (when activated) will make a query to lightrag before answering the user.

Added OpenWebui Tool

---

README.md

Fixed a broken link in Readme.md under ## API.

Fixed API docs link in Readme.md

---

lightrag/lightrag.py
lightrag/utils.py

修复当出现异常时，会导致更新数据卡死的bug

---

lightrag/api/README.md
lightrag/api/lightrag_server.py
test_lightrag_ollama_chat.py

To enhance the compatibility of the LightRAG Ollama emulation API, the following improvements have been made to the LightRAG Server:
* Determine whether the request originates from a session title or session keyword generation task in Open WebUI, and if so, directly forward the request to the underlying LLM.
* Added support for the Ollama Generate a completion API, forward the request to the underlying LLM.
* Added relevant test cases for the Ollama Generate a completion API.

Add ollama generate api support

---

lightrag/api/lightrag_server.py
lightrag/api/static/index.html
lightrag/api/webui/static/js/lightrag.js
lightrag/kg/neo4j_impl.py

translated docstrings to english and enhanced the webui

---

README.md
lightrag/lightrag.py
lightrag/operate.py

Feature:
- Query by adding your own prompt default prompt type will be of light rag
Bring your own prompt and generate response in the format you want

Query with your custom prompts

---

lightrag/api/lightrag_server.py
lightrag/utils.py

- Add CSV quoting for all fields
- Remove null characters from CSV input
- Improve CSV data integrity
- Ensure consistent CSV formatting

Enhance robustness of CVS processing ,Fix potential CSV parsing issues

---

examples/lightrag_openai_mongodb_graph_demo.py
lightrag/kg/mongo_impl.py
lightrag/lightrag.py

Add support for MongoDB as GraphStorage using $graphLookup.
Accidentally closed https://github.com/HKUDS/LightRAG/pull/654
Moved/renamed demo.py into examples/
Thank you @LarFii for quick feedback!

+ MongoDB KnowledgeGraph Support

---

lightrag/utils.py
test_lightrag_ollama_chat.py

- Fix loop step from 1 to 2 in get_conversation_turns, ensure user-assistant pairing
- Refactor conversation history handling of unit test code

Fix get conversation turns

---

README.md
examples/test_faiss.py
lightrag/kg/faiss_impl.py
lightrag/lightrag.py

This pull request introduces the integration of Faiss as a backend for vector storage in LightRAG, enhancing its capabilities for efficient similarity search and retrieval in large-scale environments. By utilizing Faiss's robust indexing features, LightRAG can now handle denser vector spaces and offer faster query response times.
- **FaissVectorDBStorage Class**: A new storage class that utilizes Faiss for storing and retrieving vectors. Supports cosine similarity through inner product searches in normalized vector spaces.
- **Embedding Functionality**: Integration of `sentence-transformers` for generating embeddings, with an option to switch to OpenAI embeddings for larger dimensions.
- **Configuration Enhancements**: Added `vector_db_storage_cls_kwargs` to allow dynamic threshold …

Implement Faiss Vector Storage Support for LightRAG

---

lightrag/api/lightrag_server.py
requirements.txt

docling is a library that allows loading: pdf, docx, pptx, xlsx files and converting the output into efficient markdown. It can perform OCR on pdfs that are not text based (scans) it can load text from images, and can load docx, pptx, xlsx files and produce a proper text that has already been cleaned for RAG.
This PR, replaces the old libraries to load these files with docling andhancing the quality of the text extraction greatly.

Use docling for enhanced files loading

---

README.md
lightrag/kg/postgres_impl.py
lightrag/lightrag.py

- Fix the bug from main stream that using doc['status']
- Improve the performance of Apache AGE.
- Revise the README.md for Apache AGE indexing.

Fix the bug from main stream that using doc['status'] and improve Apache AGE performance

---

test_lightrag_ollama_chat.py

Add http status check in unit tests.

Add http status check in unit tests.

---

lightrag/lightrag.py

fix DocStatus issue

---

lightrag/lightrag.py

This  merge request implements a temporary solution to address the issue #706

fix doc_key filtering logic to handle dict status

---

lightrag/tools/lightrag_visualizer/graph_visualizer.py

fix graph viewer crash on macos when show file dialog

---

lightrag/api/lightrag_server.py
lightrag/api/ollama_api.py

Added environment variable loading with dotenv in Ollama API

Fixing .env file loading problem for Ollama API module

---

lightrag/api/lightrag_server.py

Add keyword_extraction param support for LLM func of API Server, for more reliable keyword extraction.

fix: add keyword_extraction param support for LLM func of API Server

---

lightrag/api/lightrag_server.py
lightrag/llm/openai.py

Fix mutable default parameter issue, for better code behavior.

Fix mutable default param

---

README.md
examples/lightrag_oracle_demo.py
lightrag/base.py
lightrag/kg/json_kv_impl.py
lightrag/kg/jsondocstatus_impl.py
lightrag/kg/mongo_impl.py
lightrag/kg/oracle_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/redis_impl.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py
lightrag/operate.py
lightrag/utils.py

This pull request addresses the issue with the Pipe insert and ensures proper functioning of the following pipeline processes:
apipeline_process_documents
apipeline_process_chunks
apipeline_process_extract_graph
Additionally, the code has been cleaned up to improve clarity and maintainability, with type annotations added for better readability and robustness.
And process more document in Async way.
----
**Remarks**
@LarFii 
I have a concern regarding the project's focus.  
Initially, the primary goal was RAG Graph, but I notice an increasing number of unnecessary tool integrations, such as openwebui_tool and others etc. These additions may lead to a loss of focus and introduce extra maintenance overhead.
Would it be beneficial to reassess and streamline the scope to ensure the project …

Fixed Pipe Insert & Code Cleanup

---

lightrag/base.py
lightrag/kg/json_kv_impl.py
lightrag/kg/jsondocstatus_impl.py
lightrag/kg/mongo_impl.py
lightrag/kg/oracle_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/redis_impl.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py

After thorough testing, some bugs were identified. 
This pull request fixes them and significantly improves parallelism, making the process much faster than before.
@LarFii, when you have a moment, please review. Your feedback is appreciated! 
Please read my comments

Improve Parallelism & Fix Bugs After Testing

---

README.md
lightrag/base.py
lightrag/lightrag.py

Some documentations update to make more clear some point.

Updated documentation

---

examples/lightrag_gemini_demo.py

I integrated Gemini client into LightRAG. So users can now use Gemini too to query using LightRAG.

Integrate gemini client into Lightrag

---

examples/lightrag_api_ollama_demo.py
examples/lightrag_api_openai_compatible_demo.py
examples/lightrag_api_oracle_demo.py

Ensure insert_file API correctly handles multipart/form-data instead of JSON payload.
https://github.com/HKUDS/LightRAG/blob/6f2e1d25b34953044d9466f54b4d58df8dfa2aca/examples/lightrag_api_openai_compatible_demo.py#L135-L142
the file uploads use multipart/form-data instead of a JSON body
https://github.com/HKUDS/LightRAG/blob/6f2e1d25b34953044d9466f54b4d58df8dfa2aca/examples/lightrag_api_openai_compatible_demo.py#L178-L179

Fix incorrect usage of insert_file API

---

lightrag/api/lightrag_server.py
lightrag/lightrag.py

• Correct menu tree structure in splash screen
• Update storage check rules afther the  fixing of MilvusVectorDBStorage typo corrected

Fix typos in documentation tree structure and storage check rules

---

lightrag/api/lightrag_server.py
lightrag/lightrag.py

Some naming changes were made but were not applied due to an error during deletion.
That close : https://github.com/HKUDS/LightRAG/issues/757

Fixe the delete

---

examples/test_chromadb.py
lightrag/kg/chroma_impl.py

1. Fix embedding type conversion issue in the query function of chroma_impl; 
2. chroma_impl supports local persistent client: PersistentClient

chroma_impl supports local persistent client: PersistentClient

---

lightrag/kg/neo4j_impl.py
lightrag/operate.py

- Add label existence check and validation methods in Neo4j implementation
- Improve error handling in get_node, get_edge, and upsert methods
- Add default values and logging for missing edge properties
- Ensure consistent label processing across graph storage methods
fix for https://github.com/HKUDS/LightRAG/issues/778

Enhance Neo4j graph storage with error handling and label validation

---

.dockerignore
.gitignore

• Refactored and organized .gitignore for better readability and structure.
• Improved .dockerignore to optimize build performance and exclude unnecessary files.

Improve .gitignore and .dockerignore

---

README.md

Replaced "hf_embedding" with "hf_embed" in HuggingFace example to match implementation

Update HuggingFace example in README.md

---

.env.example
lightrag/api/README.md
lightrag/api/lightrag_server.py
lightrag/kg/faiss_impl.py
lightrag/kg/nano_vector_db_impl.py

- Fix working directory and input directory relative path problem 
- Standardization vars name for all vector database implementations
- Reorganize Ollama emulation API documentation for better readability

Fix relative path problem & standardization vars name

---

README.md
lightrag/lightrag.py
lightrag/operate.py

- Bring your own custom system prompt and do query
- Supported in all forms of search type
- If you don't pass your own system prompt, answer will be generated using lightRAG by default system prompt defined in each mode

Added system prompt support in all modes

---

lightrag/base.py
lightrag/lightrag.py

Fix of https://github.com/HKUDS/LightRAG/issues/813

Fixed str enum

---

lightrag/operate.py

This fix, remove complexity and fix keywords

Fixed keywords

---

lightrag/lightrag.py

Cleaned typing

---

lightrag/api/requirements.txt

light rag server missing an install

fixed missing install

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question.yml

Update of the templates.
See in title

Updated templates

---

lightrag/lightrag.py
lightrag/operate.py
lightrag/prompt.py

cleaned code

---

lightrag/lightrag.py
lightrag/operate.py

Improvement of parallels
- Slow of processing

Improved Paralles

---

lightrag/lightrag.py

Multi batch
- To slow
- Added multi parallele

Multi batches

---

lightrag/lightrag.py

behaviour Multi paralle when processing

fixed the behaviour Multi paralle

---

lightrag/lightrag.py

added lock

---

docker-compose.yml
examples/lightrag_api_oracle_demo.py
examples/lightrag_openai_compatible_stream_demo.py
examples/lightrag_tidb_demo.py
lightrag/kg/__init__.py
lightrag/kg/oracle_impl.py
lightrag/kg/postgres_impl.py
lightrag/lightrag.py
lightrag/utils.py
reproduce/Step_3.py
reproduce/Step_3_openai_compatible.py

Database Cleanup

---

lightrag/api/lightrag_server.py
lightrag/base.py
lightrag/kg/age_impl.py
lightrag/kg/gremlin_impl.py
lightrag/kg/mongo_impl.py
lightrag/kg/neo4j_impl.py
lightrag/kg/networkx_impl.py
lightrag/kg/oracle_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py

Revert "removed get_knowledge_graph"

---

lightrag/api/lightrag_server.py
lightrag/base.py
lightrag/kg/age_impl.py
lightrag/kg/gremlin_impl.py
lightrag/kg/mongo_impl.py
lightrag/kg/neo4j_impl.py
lightrag/kg/networkx_impl.py
lightrag/kg/oracle_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py
lightrag/tools/lightrag_visualizer/graph_visualizer.py

Revert "Cleanup of code"

---

Dockerfile
docker-compose.yml

This PR aims to simplify both the `Dockerfile` and `docker-compose.yml` files to enhance maintainability and reduce unnecessary complexity. The changes include:
1. **Dockerfile:**
- Removed the installation of build dependencies (e.g., `build-essential`, `curl`, `pkg-config`, `libssl-dev`, and Rust toolchain) that are not essential for the LightRAG's build. This reduce the build time.
2. **docker-compose.yml:**
- Simplified the configuration by removing redundant network settings (`lightrag_net`) and the `extra_hosts` configuration, which is not required for the LightRAG.
- Update environment and volume configurations to make the setup more straightforward.
These changes do not affect the core functionality of the application but improve the overall development and deployment experience.

Simplify dockerfile and docker-compose files

---

examples/lightrag_zhipu_postgres_demo.py

To fix the example of PG, to cater with new version of LightRag changes

Fix the demo issue of PG to cater with new LightRag changes

---

lightrag/operate.py
lightrag/prompt.py

Update prompt template to use the same format as in examples.
N/A
Minor adjustments to the entity extraction prompt template for consistency.
N/A

Use consistent format as in examples

---

lightrag/lightrag.py

This PR improves query caching by normalizing the input query. Previously, queries with different whitespace variations were treated as distinct, leading to unnecessary cache misses. Now, queries are trimmed and normalized to ensure consistent caching behavior.
- Normalized query input by trimming extra whitespace before caching.
- Ensured that function treats logically identical queries as the same.
- Improved cache efficiency by preventing redundant queries.
This change prevents cache misses due to trivial differences in whitespace, making the caching mechanism more efficient. Let me know if any additional refinements are needed!

Improved caching check

---

lightrag/lightrag.py

Add summary language setting by env
Modify the LightRAG class to retrieve the environment setting for the summary language and incorporate it into the addon_params.

Add summary language setting by env

---

lightrag/kg/age_impl.py
lightrag/kg/chroma_impl.py
lightrag/kg/gremlin_impl.py
lightrag/kg/milvus_impl.py
lightrag/kg/mongo_impl.py
lightrag/kg/oracle_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/qdrant_impl.py
lightrag/kg/redis_impl.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py

Completed the missing methods in various databases to support modifications for the Graph.
Many graph databases are missing the `get_all_labels` and `get_knowledge_graph` methods, while vector databases lack the `delete`-related methods.
Implemented the `get_all_labels` and `get_knowledge_graph` methods for all graph databases, and added the `delete`, `delete_entity`, and `delete_entity_relation` methods for the vector database.

Completed the missing methods in various databases to support modifications for the Graph.

---

lightrag/lightrag.py

Previously, LightRAG will launch parallel tasks  for each batch of document processing.  If one task failed, although the document processing task was marked as "Failed", other parallel tasks would continue to execute, but their results would not be accepted. This PR improves the error handling approach by actively canceling other parallel tasks when one task encounters an error.
- Created tasks with references for cancellation
- Prioritized entity relation task execution
- Implemented task cancellation on failure
- Added error logging to pipeline_status

Improved task handling and error management in LightRAG

---

lightrag/lightrag.py

Fix the issue where editing entity names does not properly update the corresponding relationship in the vdb.

[Bug]Fix the issue where editing entity names does not properly update the corresponding relationship in the vdb.

---

README.md
lightrag/lightrag.py

Added entity merging functionality to LightRAG, allowing users to combine multiple entities into a single entity while intelligently handling all relationships.
N/A
* Implemented `merge_entities` and `amerge_entities` methods that allow merging multiple source entities into a target entity
* Added support for customizable merge strategies (concatenate, keep_first, keep_last, join_unique) for different entity attributes
* Added `target_entity_data` parameter to directly specify values for the merged entity
* Implemented intelligent relationship handling:
* Redirecting all relationships from source entities to target entity
* Merging duplicate relationships with customizable strategies
* Preventing self-loops when source entities have relationships between them
* Updated vector database …

Added entity merging functionality

---

examples/test_postgres.py
lightrag/kg/postgres_impl.py

fix the postgres get all labels and get knowledge graph

---

lightrag/operate.py

Fixed entites_section_list comma error

---

env.example
lightrag/api/README.md
lightrag/api/lightrag_server.py

Add LLM cache control env for API Server

Add LLM cache control env for API Server

---

lightrag/operate.py
lightrag/prompt.py

Thanks to @YanSte. This pull request fixes iteration extraction and improves extraction. Improved continue prompt with remember, otherwise, some cases where LLM takes in the example some unrelated entities.
N/A
Modify extraction examples.
Fix `entity_continue_extraction` prompt
Fix typo
N/A

Fixed and improved Iteration extraction

---

lightrag/prompt.py

I use self-hosted `meta-llama/Llama-3.1-8B-Instruct`, modify`lightrag_api_openai_compatible_demo_simplified` to use the LLM, and run the script on 《The Project Gutenberg eBook of A Christmas Carol》, it will fail on the keyword extraction of the query. 
Debug into the code, the LLM output as below for keyword extraction. As you can see, the LLM wrote a code and tried to run it, so it will fail the JSON parser. I believe we need more strict restrictions on output formats.
```
```
https://github.com/HKUDS/LightRAG/issues/1044
add a restriction on query keywords extraction output formats, to force LLM to output a valid JSON

force keywords_extraction output as JSON

---

lightrag/kg/neo4j_impl.py
lightrag/operate.py

When extracting entities from LLM responses, we encountered issues with truncated responses that could corrupt the entire extraction process. The main problems were:
- Concatenation of potentially truncated results leading to parsing errors
- Invalid entity types being accepted
The solution involves two main improvements:
- Process each extraction result independently
- Use dictionary merging instead of string concatenation
- Added comprehensive validation for entity name, type, and description
- Implemented detailed error logging for invalid entities
- Add entity type error check for specified occasion

Improve Entity Extraction Robustness for Truncated LLM Responses

---

lightrag/lightrag.py
lightrag/operate.py
lightrag/utils.py

This pull request refactors the LightRAG codebase to improve code organization and maintainability. It moves utility functions from the main `LightRAG` class to appropriate utility modules, reducing class size and improving separation of concerns.
N/A
* Moved `_get_content_summary` from LightRAG class to `utils.py` as a standalone function
* Moved `clean_text` static method from LightRAG class to `utils.py` as a utility function
* Added standalone `check_storage_env_vars` function to `utils.py`
* Refactored keyword extraction and query logic into a dedicated `query_with_keywords` function in `operate.py`
* Updated imports and method calls throughout the codebase to use the relocated functions
* Made sure all code comments remain in English for consistency
This refactoring makes the …

Refactor LightRAG for better code organization

---

lightrag/base.py
lightrag/kg/chroma_impl.py
lightrag/kg/faiss_impl.py
lightrag/kg/milvus_impl.py
lightrag/kg/mongo_impl.py
lightrag/kg/nano_vector_db_impl.py
lightrag/kg/oracle_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/tidb_impl.py
lightrag/lightrag.py

This PR implements a standardization of vector database interfaces. Unified `get_by_id` and `get_by_ids` methods have been added to all vector database implementations, replacing the previous inconsistent approach of directly accessing internal attributes. These modifications make the code more robust and reduce dependency on implementation-specific internal details.
Resolves the error occurring when using PostgreSQL as a vector database during merge operations: `PGVectorStorage object has no attribute client`. This error occurred when the `get_entity_info` and `get_relation_info` methods attempted to access internal attributes.
1. Added new abstract methods to the base class `BaseVectorStorage`:
`get_by_id` - Retrieves vector data by a single ID
`get_by_ids` - Retrieves vector data by …

Standardizing Vector Database Interfaces

---

lightrag/api/routers/document_routes.py

Add PipelineStatusResponse model for API endpoint

Add PipelineStatusResponse model for API endpoint

---

README.md
lightrag/lightrag.py
requirements.txt

Added functionality to export knowledge graph data in multiple formats, including CSV, Excel, Markdown, and Text. Users can now export entity, relation, and vector embedding data for analysis, sharing, and backup purposes.
N/A (No related issues were referenced.)
- Implemented `export_data` function to support multiple file formats (CSV, Excel, Markdown, and Text).
- Added an option to include vector embeddings in exported data.
- Updated documentation to reflect the new export functionality.
- Provided usage examples for different file formats.
This feature enhances LightRAG's usability by allowing users to save and share structured knowledge graph data easily. Future improvements could include support for JSON and database export options.

Fixed lint and Added new imports at the top of the file

---

lightrag/api/gunicorn_config.py
lightrag/api/lightrag_server.py
lightrag/utils.py

Consolidate the two log filters into a single utility and relocate it to the utils module.

Consolidate the two log filters into a single utility and relocate it to the utils module.

---

Dockerfile
lightrag/api/requirements.txt

Update Dockerfile and API requirements for improved build and dependencies to fix the grasplogic build errors
https://github.com/HKUDS/LightRAG/issues/1057
- Add Rust installation to Dockerfile for potential performance improvements
- Set explicit Docker data directories
- Add graspologic library to API requirements
- Optimize Docker build stages and environment setup
See https://github.com/HKUDS/LightRAG/issues/1057 for detailed description of the error.

Fix graspologic build error in docker container

---

lightrag/api/docs/LightRagWithPostGRESQL.md
lightrag/lightrag.py

Replace unreasonable parameter names
Replace unreasonable parameter names
The original parameters cannot be found on the command line, which will affect the readability of the document.

Replace unreasonable parameter names

---

lightrag/kg/postgres_impl.py

Fix PGDocStatusStorage content extraction for DocProcessingStatus

Fix PGDocStatusStorage content extraction for DocProcessingStatus

---

lightrag/base.py
lightrag/kg/postgres_impl.py
lightrag/lightrag.py
lightrag/operate.py
lightrag/prompt.py

This pull request introduces enhancements to the LightRAG system by adding support for handling file paths in document processing. The changes ensure that file paths are tracked and stored throughout the document lifecycle, enabling better citation and traceability.
N/A
- Added `file_path` attribute to `DocProcessingStatus` class in `lightrag/base.py`.
- Updated `meta_fields` in `LightRAG` class to include `file_path` in `lightrag/lightrag.py`.
- Modified document insertion methods (`ainsert`, `apipeline_enqueue_documents`, etc.) to handle `file_path`.
- Ensured `file_path` is included in document status and chunk metadata.
- Updated entity and relationship extraction functions to incorporate `file_path`.
- Adjusted knowledge graph node and edge merging functions to manage `file_path`.
- …

Adding support for handling file paths in document processing. 

---

.gitattributes

- Mark webui files as binary
- Exclude webui files from diff
- Add linguist-generated flag

Update .gitattributes for webui files

---

lightrag/kg/postgres_impl.py

Implemented a not-implemented method from postgres doc status storage.

Implemented simple PSQL doc-status get_by_ids method

---

lightrag/operate.py

Fix index bug.
ERROR: Failed to process document doc-xxx: 'metadata'
Remove metadata related codes.

Fix ERROR: Failed to process document doc-xxx: 'metadata'

---

lightrag/lightrag.py

Fixed the issue where editing entities or relationships caused query failures.
TypeError: unsupported operand type(s) for +: 'DegreeView' and 'int'
After renaming an entity, the associated relationships with the old entity name are correctly deleted from the vector database.
N/A

Fixed the issue where editing entities or relationships caused query failures.

---

lightrag/utils.py

Problem: The logging configuration currently lacks flexibility incase you want to run it in a container and want to only log to STDOUT.
The change adds an `enable_file_logging` parameter to `setup_logger` which:
- When `True` (default): Sets up both console and file logging
- When `False`: Sets up console logging only, skipping all file-related operations
The change also adds better error handling for file permission issues, allowing the logger to fall back to console-only logging if it can't create log files, rather than crashing.
This makes the logging system more flexible and resilient, especially in restricted environments where file writing might not be possible or desired.

Add ability to conditionally disable file logging

---

lightrag/__init__.py
lightrag/api/__init__.py

Increment the release version to 1.2.8

Increment the release version to 1.2.8

---

README-zh.md
README.md

Fix linting in README

---

lightrag/utils.py

Increase conten summary from 100 to 250 CHARS

Increase conten summary from 100 to 250 CHARS

---

lightrag/api/lightrag_server.py
lightrag/api/run_with_gunicorn.py
lightrag/api/utils_api.py

- Show warning if .env is missing
- For CLI startup: prompt for user confirmation
- For service startup: display warning only

feat: add .env file check on startup

---

lightrag/api/utils_api.py
lightrag/utils.py
lightrag_webui/src/features/DocumentManager.tsx

Resolved the Tooltip positioning issue:
Frontend:
- Changed all Tooltip position styles from fixed to absolute
- Maintained the position: relative on parent elements (already present in the group relative class)
Backend:
- Add pipeline_status endpoint to log filter

Hotfix: Resolved the Tooltip positioning issue

---

lightrag/api/README-zh.md
lightrag/api/README.md
lightrag/api/lightrag_server.py

fix: auth_mode error in health check end point
- Change AUTH_USERNAME/PASSWORD to AUTH_ACCOUNTS format
- Update docs for new auth configuration

fix: auth_mode error in health check end point

---

lightrag/api/utils_api.py

Add core version to server startup splash screen

Add core version to server startup splash screen

---

lightrag/operate.py
lightrag/prompt.py

This pull request introduces several updates to the `lightrag/operate.py` and `lightrag/prompt.py` files. The main changes involve adding file path information to the content processing functions and updating the format for listing reference sources.
This pull request addresses issues related to the inclusion of file path information in content processing and the format of reference sources in the documentation.
- Updated `mix_kg_vector_query` function to include file path information in the chunk text.
- Modified `_get_node_data` and `_get_edge_data` functions to append file path information to the text units section list.
- Adjusted the `naive_query` function to incorporate file path information in the section content.
- Revised the reference source format in `lightrag/prompt.py` to …

fix citation

---

examples/lightrag_gemini_track_token_demo.py
examples/lightrag_siliconcloud_track_token_demo.py
lightrag/llm/openai.py
lightrag/utils.py

Introduce the TokenTracker class to record token usage in LLM calls, and add support for token_tracer in the openai_complete_if_cache function. Simultaneously add two sample files to demonstrate how to use TokenTracker in different LLM models.
#1206

feat:  Add TokenTracker to track token usage for LLM calls

---

lightrag/__init__.py

Bump core version to 1.3.1

---

lightrag/api/utils_api.py
lightrag/base.py
lightrag/lightrag.py
lightrag/operate.py

standardize .env loading behavior across modules

standardize .env loading behavior across modules

---

env.example
lightrag/api/README-zh.md
lightrag/api/README.md
lightrag/operate.py

- Remove the comments at the end of the environment variable lines in .env file
- Shorten log message to fit in pipelinestatus UI

Remove the comments at the end of the environment variable lines in .env file

---

examples/lightrag_gemini_track_token_demo.py
examples/lightrag_siliconcloud_track_token_demo.py
lightrag/utils.py

Add the ` __enter_ ` and ` __exit_ ` methods to the TokenTracker class to support context manager syntax. This can automatically reset and print token usage when using token tracking, simplify code, and improve readability. Simultaneously updated the relevant example code to use the new context manager method.

feat(TokenTracker): Add context manager support to simplify token tracking

---

lightrag/llm/openai.py

Add support for custom client configurations in the OpenAI integration, allowing for more flexible configuration of the AsyncOpenAI client. This includes:
- Create a reusable helper function `create_openai_async_client`
- Add proper documentation for client configuration options
- Ensure consistent parameter precedence across the codebase
- Update the embedding function to support client configurations
- Add example script demonstrating custom client configuration usage
The changes maintain backward compatibility while providing a cleaner and more maintainable approach to configuring OpenAI clients.
[Add …

feat(openai): add client configuration support to OpenAI integration

---

README-zh.md
README.md

Add Token Statistics Function Description in README
#1206

docs: Add Token Statistics Function Description in README

---

README.md
lightrag_webui/src/components/graph/GraphControl.tsx
lightrag_webui/src/components/graph/Settings.tsx
lightrag_webui/src/hooks/useLightragGraph.tsx
lightrag_webui/src/lib/constants.ts
lightrag_webui/src/locales/ar.json
lightrag_webui/src/locales/en.json
lightrag_webui/src/locales/fr.json
lightrag_webui/src/locales/zh.json
lightrag_webui/src/stores/settings.ts

1. Nonlinear control of edge thickness based on weight value through panel settings.
2. Fix spelling errors in README.md

Feat edge thickness

---

lightrag_webui/src/components/graph/Legend.tsx
lightrag_webui/src/components/graph/LegendButton.tsx
lightrag_webui/src/features/GraphViewer.tsx
lightrag_webui/src/hooks/useLightragGraph.tsx
lightrag_webui/src/lib/constants.ts
lightrag_webui/src/locales/ar.json
lightrag_webui/src/locales/en.json
lightrag_webui/src/locales/fr.json
lightrag_webui/src/locales/zh.json
lightrag_webui/src/stores/graph.ts
lightrag_webui/src/stores/settings.ts

1. Optimize node color generation logic
2. Add legend components and toggle buttons
#1261

Feat：Nodes of the same type are represented by the same color

---

lightrag/api/utils_api.py

Fix server splash screen format

Fix server splash screen format

---

lightrag/api/__init__.py
lightrag/kg/redis_impl.py
lightrag/operate.py

Merge PR #1258 and hange get_by_id batch size from 25 to 5 to reserve db connection resources

Merge PR #1258 and hange get_by_id batch size from 25 to 5 to reserve db connection resources

---

lightrag/api/README-zh.md
lightrag/api/README.md
lightrag/api/routers/ollama_api.py

Improve context only mode for Ollama api

Improve context only mode for Ollama api

---

lightrag/api/lightrag_server.py

Remove api tag from swagger

---

README.md

Fix linting

---

env.example
lightrag/api/config.py
lightrag/api/lightrag_server.py
lightrag/api/utils_api.py
lightrag/operate.py

- Add ENABLE_LLM_CACHE env support
- Fix mix_kg_vector_query function return value error when only_need_context is enabled

Add ENABLE_LLM_CACHE env support and fix mix_kg_vector_query return value error when only_need_context is enabled

---

lightrag/api/__init__.py
lightrag/kg/json_doc_status_impl.py
lightrag/kg/json_kv_impl.py
lightrag/kg/nano_vector_db_impl.py
lightrag/kg/networkx_impl.py
lightrag/kg/postgres_impl.py
lightrag/operate.py
lightrag/utils.py

- Fix LLM cache now work for nodes and edges merging
- Add node and edge merging log to pipeline_status

Fix LLM cache now work for nodes and edges merging

---

lightrag/operate.py

Description
Fixes a bug where file_path was not present dictionary when uploading files.

Fixes a bug where file_path was not present dictionary 

---

lightrag/llm/openai.py

支持openai中转站的base url，使得可以从环境变量获得，避免报错

add opneai llm base url

---

lightrag/lightrag.py
lightrag/operate.py

- Only merge new entities/edges during gleaning stage
- Optimize pipeline status message

Only merge new entities/edges during gleaning stage

---

lightrag_webui/src/api/lightrag.ts
lightrag_webui/src/features/RetrievalTesting.tsx

Merge PR #1331 and fix lintings

---

lightrag_webui/src/api/lightrag.ts
lightrag_webui/src/features/RetrievalTesting.tsx

Fix the issue where webui does not support stream output
#1274 #1286 
Directly connecting to the server is already supported, but using a proxy server locally is not yet possible

Fix response stream

---

lightrag_webui/src/components/AppSettings.tsx
lightrag_webui/src/i18n.ts
lightrag_webui/src/locales/zh_TW.json
lightrag_webui/src/stores/settings.ts

Add zh_TW (Traditional Chinese, Taiwan) to i18n
Thank you so much for giving me the opportunity to contribute to this project.
I'm always happy to support open source projects, even if my contributions are small.
I hope that one day I'll be able to take on more challenging tasks — I'm still learning and working towards that.
FR-#1335

docs(locales): add traditional Chinese language support 

---

lightrag/kg/postgres_impl.py
lightrag/operate.py
lightrag/utils.py
tests/test_graph_storage.py

Fix special chars handling error for PostgreSQL graph storage
- handling entity name with backslash
- handling entity name with quotes

Fix special chars handling error for PostgreSQL graph storage

---

lightrag/operate.py

`system_prompt` template was never filled with `.format()` for a `mix_kg_vector_query`
-
-
-

fix: correct parentheses. `system_prompt` was never formatted.

---

lightrag/llm/openai.py

Fix "list index out of range" issue when using "stream response" in webui
Stated as Fixed in issues/1297, but still presents in latest version.
https://github.com/HKUDS/LightRAG/issues/1297
async def openai_complete_if_cache() -> async def inner()

fix streaming "list index out of range"

---

lightrag/lightrag.py

‌[During operation] Failure to properly log exception details‌
Use traceback.format_exc() to capture comprehensive error traces when processing documents
Log verbose error context upon failures in entity/relationship extraction
Enhance system stability and debuggability by expanding exception catching and structured logging

refactor(lightrag): Optimize error handling and logging

---

lightrag_webui/src/api/lightrag.ts
lightrag_webui/src/components/retrieval/ChatMessage.tsx

Add full markdown support for query view of WebUI
Add mermaid diagram support for query view of WebUI
#1404
Using whitespace pre wrap to maintain the format /n returned by LLM is achieved by using message. message. content. replace (/\ * \ {3}/g, ''). replace (/\ {4} \ * \ */g, '* *') to ensure reasonable line breaks on the interface

Add mermaid

---

lightrag/lightrag.py

This PR introduces a new asynchronous method `aget_docs_by_ids` to the `LightRAG` class. This function allows users to query the processing status of one or more documents using their IDs. This addresses the current limitation where the `ainsert` method returns `None`, making it difficult for users to track the success or failure of the asynchronous document indexing process, especially if errors occur internally during `process_document`.
*   Added the asynchronous method `aget_docs_by_ids(self, ids: str | list[str]) -> dict[str, DocProcessingStatus]` to the `LightRAG` class.
Example Usage Pattern:
```python
doc_id = "some_document_id"
await rag.ainsert("Document content", ids=doc_id)
status_map = await rag.aget_docs_by_ids(doc_id)
if doc_id in status_map:
print(f"Status for {doc_id}: …
```

feat: Add `aget_docs_by_ids` to check document processing status

---

lightrag/operate.py
lightrag/utils.py

Revise the context format of chunks from CSV to JSON to enhance compatibility with LLM
https://github.com/HKUDS/LightRAG/issues/1405

Revise the context format of chunks from CSV to JSON to enhance compatibility with LLM

---

lightrag/kg/postgres_impl.py

Improve PostgreSQL AGE graph query by write a customized BFS implementation

Improve PostgreSQL AGE graph query by write a customized BFS implementation

---

lightrag/api/routers/document_routes.py
lightrag/lightrag.py

The improved pipeline handles logic by using semaphores to control the degree of concurrency in file processing, thus eliminating the problem of idle gaps between batches caused by batch processing. As a result, the scanning of file processing can now send all files to the pipeline for processing in one go.
After the modifications, the concurrency and efficiency of file processing and LLM requests will be significantly enhanced.
m/a

Improve parallel handling for documents processing

---

lightrag/kg/networkx_impl.py

Prioritize high-degree neighbors in BFS traversal for NetoworkX storage

Prioritize high-degree neighbors in BFS traversal for NetoworkX storage

---

lightrag/kg/faiss_impl.py

Solved dead lock problem for FAISS vector storage.

Hot Fix: solved dead lock problem for FAISS vector storage

---

lightrag/kg/faiss_impl.py
lightrag/kg/postgres_impl.py
lightrag/utils_graph.py

Minor bug fixes

---

lightrag/__init__.py
lightrag/lightrag.py
lightrag/operate.py

- Nodes and edges merging  does not block extraction stage any more.
- Improve parallel processing logic for document extraction and merging
- Optimize log message

Improve parallel processing logic for document extraction and merging

---

lightrag/kg/shared_storage.py
lightrag/utils.py

Enhance the robustness of concurrency control and scheduling logic

Enhance the robustness of concurrency control and scheduling logic

---

lightrag/llm/bedrock.py

Bedrock configuration was specific to Claude 3 haiku v1. With this change, can utilize any LLM.

Made bedrock_complete generic

---

lightrag/lightrag.py

Persistent LLM cache on error

---

lightrag/kg/postgres_impl.py
lightrag/lightrag.py

Fix JSON handling error for PostgreSQL graph storage

Fix JSON handling error for PostgreSQL graph storage

---

lightrag/kg/postgres_impl.py

Corrected Table create SQL commands - 2x commas were missed  
Added comma to end lines

Update postgres_impl.py syntax to create tables section

---

lightrag/operate.py

- Ignore chat history in vector search
- Unified vector retrieval logic for mix and naive queries

Ignore chat history in vector search

---

config.ini.example
lightrag/kg/postgres_impl.py
lightrag/llm/openai.py

Adds proper connection management for OpenAI API calls to prevent "too many open files" errors during parallel operations. This is particularly important for bulk embedding operations and parallel document processing. This PR is downstream of #1547, and can be reviewed and merged once that is merged.
N/A
- Wraps OpenAI chat completions in `async with` context manager in `openai_complete_if_cache`
- Wraps OpenAI embeddings in `async with` context manager in `openai_embed`
- Ensures proper connection cleanup after each API call
This change addresses connection management issues that can occur during parallel operations, particularly when processing large numbers of documents simultaneously. The `async with` context managers ensure proper cleanup of API connections, preventing resource …

Use Openai Client Context Manager

---

lightrag/llm/openai.py

Fix streaming problem for OpenAI

Fix streaming problem for OpenAI

---

lightrag/api/routers/query_routes.py

Update the API server to support the new parameter from the core library (PR #1032 ).
None
- Updated the API server `QueryRequest` schema to match `QueryParam` schema in core library. 
None

Reflect core library parameter update in API server

---

lightrag/lightrag.py

Adding file_path to node data in custom graph creation.
Added file_path attribute to nodes creation in custom graph insertion

Adding citation support in custom graph creation

---

README.md

This PR improves the documentation to help users avoid common initialization errors when using
LightRAG. Many users encounter cryptic error messages (`AttributeError: __aenter__` and `KeyError:
'history_messages'`) because the required initialization steps are not prominently documented.
This addresses common user confusion about initialization requirements that may not have been
formally reported as issues, but are frequently encountered by new users.
- ✨ Added a prominent "⚠️ Important: Initialization Requirements" section in the README
- 📝 Documented the two most common initialization errors with their specific causes and solutions
- 💡 Added inline comments in code examples to highlight the required initialization calls
- 🔧 Created a comprehensive "Troubleshooting" section with …

docs: Add clear initialization requirements and troubleshooting section

---

lightrag/__init__.py
lightrag/api/__init__.py
lightrag/base.py
lightrag/constants.py
lightrag/kg/neo4j_impl.py
lightrag/kg/networkx_impl.py
lightrag/kg/postgres_impl.py
lightrag/lightrag.py
lightrag/operate.py
lightrag/prompt.py

feat: Optimize document deletion performance
- To enhance performance during document deletion, new batch-get methods, `get_nodes_by_chunk_ids` and `get_edges_by_chunk_ids`, have been added to the graph storage layer (BaseGraphStorage and its implementations).
- Support for these new batch retrieval methods is currently limited to NetworkX, Neo4j, and Postgres AGE.
-  The `adelete_by_doc_id` function now leverages these methods to avoid unnecessary iteration over the entire knowledge graph, significantly improving efficiency.

feat: Optimize document deletion performance

---

lightrag/kg/postgres_impl.py
lightrag/lightrag.py
lightrag/operate.py

Resolving issue with PostgreSQL document chunk KV storage depending on vector storage
- Implement text_chunks upsert for PGKVStorage
- Add data migration from LIGHTRAG_DOC_CHUNKS to LIGHTRAG_VDB_CHUNKS
#1666

Fix: Resolving issue with PostgreSQL document chunk KV storage depending on vector storage

---

lightrag/base.py
lightrag/kg/mongo_impl.py

修复了 https://github.com/HKUDS/LightRAG/pull/1683 里面提到的“无法展开规定深度的子图”的问题
N/A
N/A

Fix nodes & edges are missing when retrieving knowledge subgraph

---

lightrag/kg/postgres_impl.py

Fix LLM cache handling for PGKVStorage to address document deletion scenarios.
- Add dynamic cache_type field
- Support mode parameter for LLM cache
- Maintain backward compatibility

Fix LLM cache handling for PGKVStorage to address document deletion scenarios

---

lightrag/kg/mongo_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/redis_impl.py

Fix LLM cache handling for Redis to address document deletion scenarios.
- Implements bulk scan for "extract" cache entries
- Maintains backward compatibility for normal IDs

Fix LLM cache handling for Redis to address document deletion scenarios

---

lightrag/api/routers/document_routes.py
lightrag/lightrag.py

﻿
添加关键日志：1.PDF文件解析是空白 2。文本块内容是空的
﻿
﻿
无
﻿
﻿
添加关键日志：1.PDF文件解析是空白 2。文本块内容是空的
﻿
﻿
- [1] Changes tested locally
- [1] Code reviewed
- [1] Documentation updated (if necessary)
﻿
﻿
添加关键日志：
1.PDF文件解析是空白
它会导致文本块是空，但队列任务继续进行
2。文本块内容是空的
它会导致任务线程执行异常
﻿

PDF文件解析是空白

---

lightrag/llm/openai.py

Fix: Ensured token tracking information is present for stream responses from OpenAI
#1746

Fix: Ensured token tracking information is present for stream responses from OpenAI

---

lightrag/kg/postgres_impl.py

- Expand entity_name length to 512 chars
- Increase source/target ID lengths
- Convert file_path to TEXT type
- Add migration logic

Increase field lengths for entity and file paths for PostgreSQL

---

lightrag/kg/postgres_impl.py

- Changed timestamp columns to naive UTC
- Store UTC timestamp to database to keep timezone handling easy
- Update  upsert and query function to properly handle timezone for all storage time
- Updated SQL templates for timestamp extraction
- Simplified timestamp migration logic

Fix: Resolve timezone handling problem in PostgreSQL storage

---

lightrag/operate.py

- Filter out empty file paths
- Handle missing file_path fields

Fix file path handling in graph operations

---

env.example
lightrag/kg/redis_impl.py
lightrag/lightrag.py
lightrag/operate.py

Enhance Redis connection handling with retries and timeouts
- Added Redis connection timeout configurations
- Implemented retry logic for Redis operations
- Updated error handling for timeout cases
- Improved connection pool management
- Added environment variable support

Enhance Redis connection handling with retries and timeouts

---

lightrag/operate.py

执行fetch_chunk_data前，任务列表先进行Id去重
`lightrag/operate.py _find_related_text_unit_from_relationships`
1. 添加一个去重方法
build_text_units_unique
2. 修改文本查询任务
先执行去重build_text_units_unique()，再执行查询fetch_chunk_data()
1. 文本块ID重复的概率很高
2. fetch_chunk_data方法中的order字段，由于线程随机，order最终值也是随机的。

Improve query for find_text_unit

---

lightrag/kg/postgres_impl.py

- Ensure VECTOR extension is available when PostgreSQL init
- Ensure AGE extension is available when PGGraphStorage init
fixed #1626

Feat: add PostgreSQL extensions for vector and AGE

---

lightrag/operate.py

- Replace simple string concatenation with build_file_path() in:
- _merge_edges_then_upsert
- _rebuild_single_entity
- _rebuild_single_relationship
- Ensures consistent deduplication, length limiting, and error handling
- Aligns with existing _merge_nodes_then_upsert implementation

refactor: unify file_path handling across merge and rebuild functions

---

lightrag/operate.py
lightrag/prompt.py

Fix: Improve keyword extraction prompt for robust JSON output.
* Emphasize strict JSON output in key extraction prompt
* Clean up prompt examples in key extraction prompt
* Log raw LLM response on JSON error

Fix: Improve keyword extraction prompt for robust JSON output.

---

lightrag/api/config.py

the line is making error because of the whitespace

Fix: corrected unterminated f-string in config.py

---

lightrag/api/routers/document_routes.py
lightrag/base.py
lightrag/kg/json_doc_status_impl.py
lightrag/kg/mongo_impl.py
lightrag/kg/postgres_impl.py
lightrag/kg/redis_impl.py
lightrag/lightrag.py
lightrag/utils.py

Previously, users calling the `/upload` endpoint or `/text`/`texts` endpoints had no way to track the processing progress of their documents. The system lacked:
- Unique tracking identifiers for document processing operations
- A unified API endpoint to query processing status
This PR implements a comprehensive track ID system that enables frontend applications to monitor document processing progress and status across all storage backends.
Implemented a complete track ID system with the following components:
- __Automatic track ID generation__ for all document processing operations
- __Prefix-based categorization__:
- `upload_` prefix for file upload operations
- `insert_` prefix for text insertion operations
- __UUID-based unique identifiers__ to prevent collisions
- …

Feat: add Document Processing Track ID Support for Frontend

---

lightrag/api/lightrag_server.py
pyproject.toml

Add graceful shutdown handling for LightRAG server
- Setup signal handlers for SIGINT/SIGTERM
- Clean up shared resources on shutdown
- Finalize shared data storage

Add graceful shutdown handling for LightRAG server

---

lightrag/kg/json_doc_status_impl.py
lightrag/kg/json_kv_impl.py

- Use workspace+namespace as final_namespace identifier
- Update all related storage operations
- Maintain backward compatibility

Fix: workspace isolation problem for json KV storage

---

env.example
lightrag/llm/jina.py
lightrag/llm/openai.py

Feat: Change embedding formats from float to base64 for efficiency
- Add base64 support for Jina embeddings
- Add base64 support for OpenAI embeddings
- Update env.example with new embedding options
- Improve Jina API error handling to show clean messages instead of HTML

Feat: Change embedding formats from float to base64 for efficiency

---

env.example
lightrag/api/lightrag_server.py
lightrag/constants.py
lightrag/lightrag.py
lightrag/utils.py

This PR introduces a comprehensive timeout handling system for LightRAG's concurrent LLM request processing, addressing critical production issues including race conditions, resource leaks, and infinite waiting scenarios. The implementation provides a robust, multi-layer timeout protection system that significantly improves system reliability and production readiness.
Add temperature guidance for Qwen3 30B LLM models in env example. To mitigate endless output loops or long run output, set the temperature parameter to a value between 0.8 and 1.0. A higher temperature can prevent greedy decoding that lead to long run output that make LLM timeout frequently.
1. **Race Conditions** - Future cancellation and worker processing occurring simultaneously, leading to inconsistent task states and …

refac: Enhanced Timeout Handling for LLM Priority Queue

---

lightrag_webui/src/features/DocumentManager.tsx

- Add metadata formatting with timestamps
- Replace warning emoji with proper icons
- Show tooltips for errors and metadata
- Import AlertTriangle and Info icons
- Improve status cell layout and styling

feature: Enhance document status display with metadata tooltips and better icons

---

env.example

fix example typo
small exmaple fix

fix env file example

---

lightrag/prompt.py

Remove angle brackets from entity and relationship output formats for small params LLM to do a better job.

Prompt Optimization: remove angle brackets from entity and relationship output formats

---

lightrag/operate.py

Enhanced error handling in the entity extraction pipeline by adding contextual information to exceptions during chunk processing. 
- Exceptions now include the specific chunk_id that caused the failure. 
- Easier to identify problematic document chunks in production
- No breaking changes to existing functionality
- **File**: `lightrag/operate.py`
- **Function**: `_process_with_semaphore` in `extract_entities`
- **Enhancement**: Added try-catch block to capture exceptions during chunk processing and prefix them with chunk_id for better debugging

Refactor: Add error handling with chunk ID prefixing in entity extraction

---

lightrag/__init__.py
lightrag/api/__init__.py
lightrag/operate.py
lightrag_webui/src/features/DocumentManager.tsx

This PR resolves the critical UI freezing issue while significantly improving the overall robustness and user experience of the DocumentManager component.
The DocumentManager interface would sometimes become grayed out and unresponsive, particularly when document list refresh operations encountered timeouts or errors. Users reported that the interface would remain disabled without proper error feedback or recovery mechanisms.
The primary issue was in the `startPollingInterval` function where polling errors didn't reset the `isRefreshing` state, causing the UI to remain in a disabled state indefinitely. Additional investigation revealed several areas lacking robust error handling:
- Missing error state recovery in polling mechanisms
- No timeout protection for API calls
- Insufficient …

Fix: Resolve DocumentManager UI freezing and enhance error handling

---

lightrag/api/routers/document_routes.py

• Add validate_file_path_security function
• Prevent path traversal attacks
• Validate file paths before deletion
• Check both input and enqueued dirs
• Log security violations
fix #2110

Add path traversal security validation for file deletion operations

---

lightrag_webui/src/App.tsx
lightrag_webui/src/components/graph/GraphSearch.tsx
lightrag_webui/src/features/GraphViewer.tsx

Web UI - center the loading icon and adjust GraphSeach width

---

lightrag_webui/src/hooks/useLightragGraph.tsx

web_ui: check node source and target
